import React from 'react';
import { PRODUCT_BRAND } from '../config/brand';

export function ProductBrand({compact=false,inverse=false}:{compact?:boolean;inverse?:boolean}){return <div className="flex items-center gap-2.5"><img src={PRODUCT_BRAND.icon} alt="ProcuraFlow" className={compact?'h-8 w-8':'h-11 w-11'}/><div><div className={`${compact?'text-base':'text-xl'} font-bold leading-tight ${inverse?'text-white':'text-slate-900'}`}>{PRODUCT_BRAND.name}</div><div className={`text-[10px] ${inverse?'text-slate-400':'text-slate-500'}`}>{PRODUCT_BRAND.tagline}</div></div></div>}
export function CompanyLogo({company,src,size='document',className=''}:{company?:any;src?:string|null;size?:'nav'|'compact'|'dashboard'|'document'|'report';className?:string}){const source=src||company?.logo_url;if(!source)return null;const sizes={nav:'h-8 w-12',compact:'h-9 w-14',dashboard:'h-14 w-14',document:'h-20 w-28',report:'h-16 w-24'};return <img src={source} alt={`${company?.name||company?.company_name||'Company'} logo`} className={`company-logo ${sizes[size]} shrink-0 object-contain ${className}`}/>;}
export function CompanyBrand({company,compact=false,inverse=false}:{company:any;compact?:boolean;inverse?:boolean}){return <div className="flex min-w-0 items-center gap-3">{company?.logo_url?<CompanyLogo company={company} size={compact?'compact':'report'} className="rounded bg-white p-1"/>:<div className={`${compact?'h-9 w-9':'h-16 w-16'} shrink-0 rounded-lg bg-white/10 flex items-center justify-center font-bold ${inverse?'text-white':'text-indigo-700'}`}>{String(company?.name||company?.company_name||'C').charAt(0)}</div>}<div className="min-w-0"><div className={`truncate font-semibold ${inverse?'text-white':'text-slate-900'}`}>{company?.name||company?.company_name||'Company Name'}</div>{!compact&&company?.address&&<div className={`text-xs whitespace-pre-line ${inverse?'text-slate-300':'text-slate-600'}`}>{company.address}</div>}</div></div>}
export function CompanyContact({company}:{company:any}){const contacts=[company?.phone,company?.email,company?.website].filter(Boolean);return <>{contacts.length>0&&<div className="text-xs text-slate-600">{contacts.join(' | ')}</div>}{(company?.tax_info||company?.registration_number)&&<div className="text-xs text-slate-600">{[company.tax_info&&`Tax/VAT: ${company.tax_info}`,company.registration_number&&`Registration: ${company.registration_number}`].filter(Boolean).join(' | ')}</div>}{company?.branch_info&&<div className="text-xs text-slate-600">Branch: {company.branch_info}</div>}</>}
export function DocumentCompanyHeader({company,title,reference,date,fiscalYear}:{company:any;title:string;reference?:string;date?:string;fiscalYear?:string;tone?:string}){return <header className="flex justify-between gap-6 border-b-2 border-indigo-700 pb-5"><div><CompanyBrand company={company}/><div className="ml-[92px] -mt-5"><CompanyContact company={company}/></div></div><div className="shrink-0 text-right"><div className="text-2xl font-bold tracking-wide text-indigo-950">{title}</div>{reference&&<div className="mt-2 text-sm font-semibold">{reference}</div>}{date&&<div className="text-xs text-slate-600">Date: {date}</div>}<div className="text-xs text-slate-600">Fiscal Year: {fiscalYear||company?.financial_year||'Not configured'}</div></div></header>}
export function GeneratedByFooter({note}:{note?:string}){return <footer className="print-avoid-break mt-8 border-t-2 border-slate-700 pt-3 text-[10px] text-slate-600">{note&&<div className="mb-2 text-center">{note}</div>}<div className="flex items-center justify-between gap-4 rounded-md bg-slate-100 px-3 py-2"><div className="flex items-center gap-2"><img src={PRODUCT_BRAND.icon} alt="ProcuraFlow product logo" className="h-7 w-7 object-contain"/><div><div className="text-[8px] font-semibold uppercase tracking-[.15em] text-slate-500">Powered by</div><strong className="text-sm leading-none text-indigo-950">{PRODUCT_BRAND.name}</strong></div></div><div className="text-right"><strong className="text-slate-700">{PRODUCT_BRAND.fullName}</strong><span className="print-page-number ml-3"/></div></div></footer>}
