import React from 'react';
import { getStoredCurrency } from '../utils/currency';
import { CompanyContact, CompanyLogo, GeneratedByFooter } from './Branding';
import { ResponsibleSignature } from './EmployeeSignature';

const number = (value: unknown) => Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const date = (value: unknown) => value ? new Date(String(value)).toLocaleDateString() : '—';

export default function ProfessionalGoodsReceiptNote({ grn }: { grn: any }) {
  const currency = grn.company?.currency || getStoredCurrency();
  const totalReceived = grn.items.reduce((sum: number, line: any) => sum + Number(line.quantity_received), 0);
  const totalAccepted = grn.items.reduce((sum: number, line: any) => sum + Number(line.accepted_qty), 0);
  const totalRejected = grn.items.reduce((sum: number, line: any) => sum + Number(line.rejected_qty), 0);
  const acceptedNet = grn.items.reduce((sum:number,line:any)=>sum+Number(line.accepted_qty)*Number(line.unit_cost),0);
  const acceptedTax = grn.items.reduce((sum:number,line:any)=>sum+Number(line.accepted_qty)*Number(line.unit_cost)*Number(line.po_tax||0)/100,0);
  return (
    <article id="grn-print-document" className="controlled-print-document rounded-lg border border-slate-200 bg-white p-7 text-slate-900">
      <header className="flex justify-between gap-6 border-b-2 border-blue-800 pb-5">
        <div className="flex min-w-0 gap-4"><CompanyLogo company={grn.company} size="document"/><div><h1 className="text-xl font-bold text-blue-950">{grn.company?.name || 'Company Name'}</h1><div className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{grn.company?.address || 'Company address not configured'}</div><CompanyContact company={grn.company}/></div></div>
        <div className="shrink-0 text-right"><div className="text-2xl font-bold tracking-wide text-blue-950">GOODS RECEIPT NOTE</div><div className="mt-2 text-sm font-bold">{grn.grn_number}</div><div className="text-xs text-slate-600">Receipt Date: {date(grn.grn_date || grn.created_at)}</div><div className="text-xs text-slate-600">Fiscal Year: {grn.company?.financial_year || '—'}</div></div>
      </header>
      <section className="my-5 grid grid-cols-2 gap-5 text-xs">
        <div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-blue-50 px-3 py-2 font-bold uppercase tracking-wide text-blue-950">Vendor / Supplier</div><div className="space-y-1 p-3"><div className="text-sm font-bold">{grn.supplier_name}</div><div className="whitespace-pre-line">{grn.supplier_address || 'Address not recorded'}</div>{grn.supplier_contact_person && <div>Contact: {grn.supplier_contact_person}</div>}{grn.supplier_phone && <div>Phone: {grn.supplier_phone}</div>}{grn.supplier_email && <div>Email: {grn.supplier_email}</div>}</div></div>
        <div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-blue-50 px-3 py-2 font-bold uppercase tracking-wide text-blue-950">Receipt References</div><div className="grid grid-cols-[120px_1fr] gap-y-2 p-3"><span className="text-slate-500">PO Number</span><strong>{grn.po_number}</strong><span className="text-slate-500">Committed Delivery</span><strong>{grn.committed_delivery_date || 'Not specified'}</strong><span className="text-slate-500">Delivery Note</span><strong>{grn.delivery_note || 'Not provided'}</strong><span className="text-slate-500">GRN Status</span><strong className="text-emerald-700">POSTED</strong><span className="text-slate-500">Received By</span><strong>{grn.received_by_name || '—'}</strong><span className="text-slate-500">Payment Terms</span><strong>{grn.supplier_payment_terms || 'Not specified'}</strong></div></div>
      </section>
      <table className="w-full border-collapse text-[10px]"><thead><tr className="bg-blue-900 text-white"><th className="border border-blue-800 p-2 text-center">#</th><th className="border border-blue-800 p-2 text-left">Item</th><th className="border border-blue-800 p-2 text-right">Received</th><th className="border border-blue-800 p-2 text-right">Accepted</th><th className="border border-blue-800 p-2 text-right">Rejected</th><th className="border border-blue-800 p-2 text-left">Batch / Expiry</th><th className="border border-blue-800 p-2 text-left">Warehouse</th><th className="border border-blue-800 p-2 text-right">PO Unit Cost</th><th className="border border-blue-800 p-2 text-right">PO Tax</th><th className="border border-blue-800 p-2 text-right">Accepted Gross Value</th></tr></thead><tbody>{grn.items.map((line: any, index: number) => { const uom=line.purchase_uom||line.uom||''; return <tr key={line.id} className={index%2?'bg-slate-50':'bg-white'}><td className="border border-slate-300 p-2 text-center">{index+1}</td><td className="border border-slate-300 p-2"><strong>{line.item_code}</strong><div className="text-slate-600">{line.description}</div>{line.rejection_reason && <div className="mt-1 text-rose-700">Rejection: {line.rejection_reason}</div>}</td><td className="border border-slate-300 p-2 text-right">{number(line.quantity_received)} {uom}</td><td className="border border-slate-300 p-2 text-right">{number(line.accepted_qty)} {uom}</td><td className="border border-slate-300 p-2 text-right">{number(line.rejected_qty)} {uom}</td><td className="border border-slate-300 p-2">{line.batch || '—'}<div className="text-slate-500">{date(line.expiry_date)}</div></td><td className="border border-slate-300 p-2">{line.warehouse_name}</td><td className="border border-slate-300 p-2 text-right">{number(line.unit_cost)}</td><td className="border border-slate-300 p-2 text-right">{number(line.po_tax)}%</td><td className="border border-slate-300 p-2 text-right font-medium">{number(line.accepted_line_value)}</td></tr>;})}</tbody></table>
      <section className="mt-4 flex justify-between gap-6 text-xs"><div className="grid grid-cols-2 gap-x-6 gap-y-1 rounded-md border border-slate-300 p-3"><span>Total received</span><strong className="text-right">{number(totalReceived)}</strong><span>Total accepted</span><strong className="text-right text-emerald-700">{number(totalAccepted)}</strong><span>Total rejected</span><strong className="text-right text-rose-700">{number(totalRejected)}</strong></div><div className="w-80 rounded border border-blue-200 bg-blue-50 p-3"><div className="grid grid-cols-2 gap-y-1"><span>Accepted net</span><strong className="text-right">{currency} {number(acceptedNet)}</strong><span>PO tax</span><strong className="text-right">{currency} {number(acceptedTax)}</strong><span className="border-t border-blue-300 pt-2 font-bold">Accepted gross</span><strong className="border-t border-blue-300 pt-2 text-right text-base text-blue-950">{currency} {number(acceptedNet+acceptedTax)}</strong></div><div className="mt-2 text-right text-[10px] text-slate-500">Commercial values are inherited from the approved PO. Payable value remains subject to invoice verification.</div></div></section>
      <section className="mt-14 grid grid-cols-3 gap-8 text-center text-xs"><ResponsibleSignature label="Received by" name={grn.received_by_name} src={grn.received_by_signature_url} date={grn.created_at || grn.grn_date}/><ResponsibleSignature label="Vendor Representative"/><ResponsibleSignature label="Finance Verification"/></section>
      <GeneratedByFooter note="This GRN confirms physical receipt and inspection quantities against the referenced PO. It supports invoice verification and does not by itself authorize payment."/>
    </article>
  );
}
