import React from 'react';
import { CompanyContact, CompanyLogo, GeneratedByFooter } from './Branding';
import { ResponsibleSignature } from './EmployeeSignature';

const qty=(value:unknown)=>Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString():'—';

export default function ProfessionalWarehouseTransfer({transfer,company,mode}:{transfer:any;company:any;mode:'dispatch'|'receipt'}){
 const receipt=mode==='receipt',title=receipt?'INTER-WAREHOUSE RECEIVING CONFIRMATION':'WAREHOUSE TRANSFER DISPATCH NOTE';
 const reference=receipt?transfer.receipt_number:transfer.transfer_number;
 return <article id={receipt?'transfer-receipt-print-document':'transfer-dispatch-print-document'} className="controlled-print-document rounded-lg border border-slate-200 bg-white p-7 text-slate-900">
  <header className="flex justify-between gap-6 border-b-2 border-emerald-800 pb-5"><div className="flex min-w-0 gap-4"><CompanyLogo company={company} size="document"/><div><h1 className="text-xl font-bold text-emerald-950">{company?.name||company?.company_name||'Company Name'}</h1><div className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{company?.address||'Company address not configured'}</div><CompanyContact company={company}/></div></div><div className="shrink-0 text-right"><div className="text-xl font-bold tracking-wide text-emerald-950">{title}</div><div className="mt-2 text-sm font-bold">{reference}</div><div className="text-xs text-slate-600">{receipt?'Received':'Dispatched'}: {date(receipt?transfer.received_at:transfer.dispatched_at)}</div><div className="text-xs text-slate-600">Status: {receipt?'RECEIVED':'IN TRANSIT'}</div></div></header>
  <section className="my-5 grid grid-cols-2 gap-5 text-xs"><div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-emerald-50 px-3 py-2 font-bold uppercase tracking-wide text-emerald-950">Dispatch From</div><div className="grid grid-cols-[90px_1fr] gap-y-2 p-3"><span className="text-slate-500">Warehouse</span><strong>{transfer.from_warehouse_name}</strong><span className="text-slate-500">Physical Bin</span><strong>{transfer.from_location_code||'—'}</strong><span className="text-slate-500">Dispatched By</span><strong>{transfer.dispatched_by_name||'—'}</strong></div></div><div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-emerald-50 px-3 py-2 font-bold uppercase tracking-wide text-emerald-950">Deliver To</div><div className="grid grid-cols-[90px_1fr] gap-y-2 p-3"><span className="text-slate-500">Warehouse</span><strong>{transfer.to_warehouse_name}</strong><span className="text-slate-500">Physical Bin</span><strong>{transfer.to_location_code||'To be confirmed by receiver'}</strong><span className="text-slate-500">Received By</span><strong>{receipt?transfer.received_by_name||'—':'Awaiting receiving confirmation'}</strong></div></div></section>
  <table className="w-full border-collapse text-xs"><thead><tr className="bg-emerald-900 text-white"><th className="border border-emerald-800 p-2 text-left">Transfer</th><th className="border border-emerald-800 p-2 text-left">Item Code</th><th className="border border-emerald-800 p-2 text-left">Description</th><th className="border border-emerald-800 p-2 text-right">Quantity</th></tr></thead><tbody><tr><td className="border border-slate-300 p-2 font-semibold">{transfer.transfer_number}</td><td className="border border-slate-300 p-2 font-semibold">{transfer.item_code}</td><td className="border border-slate-300 p-2">{transfer.description}</td><td className="border border-slate-300 p-2 text-right font-semibold">{qty(transfer.quantity)}</td></tr></tbody></table>
  <section className="mt-5 grid grid-cols-2 gap-5 text-xs"><div className="rounded border border-slate-300 p-3"><div className="font-bold text-emerald-900">Transport Details</div><div className="mt-2 grid grid-cols-[110px_1fr] gap-y-1"><span>Mode</span><strong>{transfer.transport_mode||'—'}</strong><span>Vehicle</span><strong>{transfer.vehicle_reference||'—'}</strong><span>Driver / Custodian</span><strong>{transfer.driver_name||'—'}</strong><span>Tracking Ref.</span><strong>{transfer.tracking_reference||'—'}</strong></div></div><div className="rounded border border-slate-300 p-3"><div className="font-bold text-emerald-900">{receipt?'Receipt Confirmation':'Transfer Instructions'}</div><p className="mt-2 whitespace-pre-line text-slate-700">{receipt?(transfer.receiving_note||'The receiving warehouse confirms the stated items and quantity were physically received.'):(transfer.remarks||'Stock is in transit and remains pending until the destination warehouse posts its receiving confirmation.')}</p></div></section>
  <section className="mt-14 grid grid-cols-3 gap-8 text-center text-xs"><ResponsibleSignature label="Dispatched by" name={transfer.dispatched_by_name} date={transfer.dispatched_at}/><ResponsibleSignature label="Transport custodian" name={transfer.driver_name}/><ResponsibleSignature label={receipt?'Received and confirmed by':'Receiving warehouse confirmation'} name={receipt?transfer.received_by_name:undefined} date={receipt?transfer.received_at:undefined}/></section>
  <GeneratedByFooter note={receipt?'Separate inter-warehouse receiving confirmation. This document is not a supplier Goods Receipt Note (GRN).':'Controlled evidence of stock dispatched between warehouses. Destination inventory is not increased until a separate receiving confirmation is posted.'}/>
 </article>;
}
