const fs=require('fs'),path=require('path'),{spawn,spawnSync}=require('child_process'),Database=require('better-sqlite3'),bcrypt=require('bcryptjs');
const root=path.resolve(__dirname,'..'),testDir=path.join(root,'test-artifacts'),testDb=path.join(testDir,'ProcuraFlow_TEST.db');fs.mkdirSync(testDir,{recursive:true});
for(const suffix of ['','-wal','-shm'])try{fs.rmSync(testDb+suffix,{force:true})}catch{}
const live=new Database(path.join(root,'procuraflow.db'),{readonly:true});live.backup(testDb).then(run).catch(e=>{console.error(e);process.exit(1)});
async function run(){live.close();const db=new Database(testDb);db.pragma('foreign_keys=ON');const wh=db.prepare('SELECT id,name FROM warehouses WHERE deleted_at IS NULL ORDER BY id').all();if(wh.length<2)throw Error('At least two warehouses required');const assigned=wh[0],denied=wh[1];
 const user=db.prepare("SELECT u.*,e.permission_keys FROM users u JOIN employees e ON e.id=u.employee_id WHERE u.role='Storekeeper' AND u.is_active=1 ORDER BY u.id LIMIT 1").get();if(!user)throw Error('Active Storekeeper required');db.prepare('UPDATE employee_warehouse_assignments SET active_yn=0 WHERE employee_id=?').run(user.employee_id);db.prepare(`INSERT OR REPLACE INTO employee_warehouse_assignments(employee_id,warehouse_id,primary_warehouse_yn,all_warehouses_yn,active_yn,effective_from) VALUES(?,?,1,0,1,date('now'))`).run(user.employee_id,assigned.id);db.prepare('UPDATE employees SET warehouse_id=?,permission_keys=? WHERE id=?').run(assigned.id,JSON.stringify(['task.grn','task.material_issue','task.returns','task.inventory','task.tools','report.inventory','report.warehouse','report.employee','report.tools']),user.employee_id);db.prepare('UPDATE users SET warehouse_id=? WHERE id=?').run(assigned.id,user.id);
 const supplier=db.prepare('SELECT id FROM suppliers WHERE deleted_at IS NULL LIMIT 1').get();const item=db.prepare('SELECT id FROM items WHERE deleted_at IS NULL LIMIT 1').get();let deniedBin=db.prepare("SELECT id FROM locations WHERE warehouse_id=? AND type='Bin' AND deleted_at IS NULL LIMIT 1").get(denied.id);let assignedBin=db.prepare("SELECT id FROM locations WHERE warehouse_id=? AND type='Bin' AND deleted_at IS NULL LIMIT 1").get(assigned.id);const makeBin=(warehouse,label)=>({id:Number(db.prepare("INSERT INTO locations(warehouse_id,type,code,label,status) VALUES(?,'Bin',?,?,'Available')").run(warehouse,`WH-${warehouse}-TEST-BIN`,label).lastInsertRowid)});if(!deniedBin)deniedBin=makeBin(denied.id,'Denied test Bin');if(!assignedBin)assignedBin=makeBin(assigned.id,'Assigned test Bin');if(!supplier||!item)throw Error('Test masters unavailable');
 const fakePo=db.prepare("INSERT INTO purchase_orders(po_number,supplier_id,po_date,status,total_amount,created_by) VALUES('PO-TEST-DENIED',?,date('now'),'Approved',1,?)").run(supplier.id,user.id).lastInsertRowid;db.prepare('INSERT INTO po_items(po_id,item_id,quantity,price,tax) VALUES(?,?,1,1,0)').run(fakePo,item.id);const fakeGrn=db.prepare("INSERT INTO grns(grn_number,po_id,supplier_id,delivery_note,created_by) VALUES('GRN-TEST-DENIED',?,?,?,?)").run(fakePo,supplier.id,'test',user.id).lastInsertRowid;db.prepare('INSERT INTO grn_items(grn_id,item_id,quantity_received,accepted_qty,rejected_qty,unit_cost,warehouse_id,location_id) VALUES(?,?,1,1,0,1,?,?)').run(fakeGrn,item.id,denied.id,deniedBin.id);db.prepare("INSERT INTO document_attachments(document_type,document_id,original_name,stored_name,mime_type,file_size,uploaded_by) VALUES('GRN',?,'denied.pdf','not-needed.pdf','application/pdf',1,?)").run(fakeGrn,user.id);db.close();
 const port=4100,server=spawn(process.execPath,['dist/server.js'],{cwd:root,env:{...process.env,DB_PATH:testDb,PORT:String(port),NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});await waitHealth(port);
 process.env.DB_PATH=testDb;const {signToken}=require('../dist/middleware/auth');const token=signToken({id:user.id,username:user.username,role:user.role,full_name:user.full_name,warehouse_id:assigned.id,warehouse_ids:[assigned.id],permission_keys:['task.grn','task.material_issue','task.returns','task.inventory','task.tools','report.inventory','report.warehouse','report.employee','report.tools']});const H={Authorization:'Bearer '+token,'Content-Type':'application/json'};const results=[];const record=(suite,name,api,expected,actual,pass,evidence)=>results.push({suite,name,api,expected,actual,status:pass?'PASS':'FAIL',evidence});
 const endpoints=['stock-balance','fifo-valuation','grn-register','daily-receiving','daily-issues','returns-report','transfers-report','adjustments-report','stock-ledger','batch-report','cycle-count-accuracy','outstanding-returnables','tool-condition','consumption-by-employee','consumption-by-department'];
 for(const ep of endpoints){const r=await fetch(`http://127.0.0.1:${port}/api/reports/${ep}?warehouse_id=${denied.id}`,{headers:H}),rows=await r.json();const text=JSON.stringify(rows),leak=text.includes(`"warehouse_name":"${denied.name.replaceAll('"','\\"')}"`);record('WAREHOUSE_ACCESS',`Scope ${ep}`,`/api/reports/${ep}`,`No ${denied.name} data`,`${r.status}; ${Array.isArray(rows)?rows.length:'error'} rows`,r.status===200&&!leak,'Tampered warehouse_id query ignored; server assignment applied');}
 for(const [name,url] of [['Direct denied GRN',`/api/warehouse/grns/${fakeGrn}`],['Denied attachment list',`/api/attachments/GRN/${fakeGrn}`]]){const r=await fetch(`http://127.0.0.1:${port}${url}`,{headers:H});record('WAREHOUSE_ACCESS',name,url,'404/403',String(r.status),[403,404].includes(r.status),'Direct ID outside assigned warehouse rejected');}
 const test=dbOpen();const poNo='PO-TEST-CONCURRENT',po=test.prepare('INSERT INTO purchase_orders(po_number,supplier_id,po_date,status,total_amount,created_by) VALUES(?,?,date(\'now\'),\'Approved\',10,?)').run(poNo,supplier.id,user.id).lastInsertRowid;test.prepare('INSERT INTO po_items(po_id,item_id,quantity,price,tax) VALUES(?,?,10,1,0)').run(po,item.id);test.close();const body=q=>JSON.stringify({po_id:Number(po),warehouse_id:assigned.id,delivery_note:'concurrency',items:[{item_id:item.id,quantity_received:q,accepted_qty:q,rejected_qty:0,location_id:assignedBin.id}]});const pair=await Promise.all([8,7].map(q=>fetch(`http://127.0.0.1:${port}/api/warehouse/grns`,{method:'POST',headers:H,body:body(q)})));const codes=pair.map(r=>r.status),check=dbOpen(),accepted=check.prepare('SELECT COALESCE(SUM(gi.accepted_qty),0) n FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.po_id=?').get(po).n;check.close();record('CONCURRENCY','Concurrent GRN over-receipt','POST /api/warehouse/grns','Only one succeeds; total <=10',`${codes.join('/')}; accepted=${accepted}`,codes.filter(x=>x===201).length===1&&accepted<=10,'Immediate transaction rechecks outstanding quantity');
 const workers=Array.from({length:12},()=>new Promise(resolve=>{const p=spawn(process.execPath,['scripts/number-worker.cjs',testDb,'PR'],{cwd:root});let out='';p.stdout.on('data',d=>out+=d);p.on('close',c=>resolve({c,out}))}));const nums=(await Promise.all(workers)).map(x=>x.out.trim()).filter(Boolean),unique=new Set(nums);record('CONCURRENCY','Concurrent document numbering','nextDocNumber(PR)','12 unique numbers',`${nums.length} returned; ${unique.size} unique`,nums.length===12&&unique.size===12,'Immediate counter transaction');
 const verify=dbOpen();verify.prepare('DELETE FROM control_test_results').run();const ins=verify.prepare('INSERT INTO control_test_results(test_suite,test_name,report_api,test_user,assigned_warehouse,requested_warehouse,expected_result,actual_result,status,evidence) VALUES(?,?,?,?,?,?,?,?,?,?)');for(const x of results)ins.run(x.suite,x.name,x.api,user.username,assigned.name,denied.name,x.expected,x.actual,x.status,x.evidence);const integrity=verify.pragma('integrity_check')[0].integrity_check,fk=verify.pragma('foreign_key_check').length;record('WORKFLOW_REGRESSION','Isolated database integrity','SQLite','ok / 0 FK',`${integrity} / ${fk}`,integrity==='ok'&&!fk,'Post-test isolated DB validation');verify.close();server.kill();
 fs.writeFileSync(path.join(testDir,'phase2-test-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({testDb,passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,results},null,2));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
 function dbOpen(){return new Database(testDb)}
}
async function waitHealth(port){for(let i=0;i<40;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/health`);if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,250))}throw Error('Test server did not start')}
