import db from './index';

type Check = { name: string; rows: unknown[] };
const checks: Check[] = [
  { name: 'foreign-key violations', rows: db.pragma('foreign_key_check') as unknown[] },
  { name: 'negative stock balances', rows: db.prepare('SELECT id,item_id,warehouse_id,quantity FROM inventory_stock WHERE quantity < 0').all() },
  { name: 'negative FIFO layers', rows: db.prepare('SELECT id,item_id,warehouse_id,quantity_remaining FROM inventory_layers WHERE quantity_remaining < 0').all() },
  { name: 'stock/FIFO mismatches', rows: db.prepare(`
    WITH stock AS (
      SELECT item_id,warehouse_id,location_id,SUM(quantity) quantity
      FROM inventory_stock GROUP BY item_id,warehouse_id,location_id
    ), layers AS (
      SELECT item_id,warehouse_id,location_id,SUM(quantity_remaining) layer_quantity
      FROM inventory_layers GROUP BY item_id,warehouse_id,location_id
    ), balance_keys AS (
      SELECT item_id,warehouse_id,location_id FROM stock
      UNION SELECT item_id,warehouse_id,location_id FROM layers
    )
    SELECT k.item_id,k.warehouse_id,k.location_id,COALESCE(s.quantity,0) quantity,COALESCE(l.layer_quantity,0) layer_quantity
    FROM balance_keys k
    LEFT JOIN stock s ON s.item_id=k.item_id AND s.warehouse_id=k.warehouse_id AND s.location_id IS k.location_id
    LEFT JOIN layers l ON l.item_id=k.item_id AND l.warehouse_id=k.warehouse_id AND l.location_id IS k.location_id
    WHERE ABS(COALESCE(s.quantity,0)-COALESCE(l.layer_quantity,0))>0.0001`).all() },
  { name: 'orphan material issues', rows: db.prepare('SELECT mi.id,mi.issue_number FROM material_issues mi LEFT JOIN material_issue_items x ON x.issue_id=mi.id GROUP BY mi.id HAVING COUNT(x.id)=0').all() },
  { name: 'invalid GRN splits', rows: db.prepare('SELECT id,grn_id FROM grn_items WHERE ABS(quantity_received-accepted_qty-rejected_qty)>0.0001').all() },
  { name: 'GRN unit costs differing from approved PO', rows: db.prepare(`SELECT gi.id,g.grn_number,po.po_number,i.item_code,gi.unit_cost grn_unit_cost,pi.price po_unit_cost FROM grn_items gi JOIN grns g ON g.id=gi.grn_id JOIN purchase_orders po ON po.id=g.po_id JOIN po_items pi ON pi.po_id=po.id AND pi.item_id=gi.item_id JOIN items i ON i.id=gi.item_id WHERE ABS(gi.unit_cost-pi.price)>.0001`).all() },
  { name: 'posted issue FIFO usage mismatches', rows: db.prepare(`SELECT mii.id,mi.issue_number,mii.quantity,COALESCE(SUM(u.quantity),0) fifo_quantity FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id LEFT JOIN material_issue_layer_usage u ON u.material_issue_item_id=mii.id WHERE mi.status='Posted' GROUP BY mii.id HAVING ABS(mii.quantity-COALESCE(SUM(u.quantity),0))>0.0001`).all() },
  { name: 'GRN receipt ledger quantity mismatches', rows: db.prepare(`SELECT gi.id,g.grn_number,gi.accepted_qty,COALESCE((SELECT SUM(sl.quantity_change) FROM stock_ledger sl WHERE sl.reference_table='grns' AND sl.reference_id=g.id AND sl.item_id=gi.item_id AND sl.warehouse_id=gi.warehouse_id AND sl.location_id IS gi.location_id AND sl.transaction_type='GRN_RECEIPT'),0) ledger_quantity FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.created_at>=datetime('now','-1 minute') AND ABS(gi.accepted_qty-COALESCE((SELECT SUM(sl.quantity_change) FROM stock_ledger sl WHERE sl.reference_table='grns' AND sl.reference_id=g.id AND sl.item_id=gi.item_id AND sl.warehouse_id=gi.warehouse_id AND sl.location_id IS gi.location_id AND sl.transaction_type='GRN_RECEIPT'),0))>0.0001`).all() },
  { name: 'over-returned items', rows: db.prepare(`SELECT r.employee_id,r.item_id,SUM(r.quantity) returned,COALESCE((SELECT SUM(mii.quantity) FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id WHERE mi.employee_id=r.employee_id AND mii.item_id=r.item_id AND mi.status='Posted'),0) issued FROM returns r GROUP BY r.employee_id,r.item_id HAVING returned>issued+0.0001`).all() },
  { name: 'duplicate PR numbers', rows: db.prepare('SELECT pr_number,COUNT(*) count FROM purchase_requisitions GROUP BY pr_number HAVING count>1').all() },
  { name: 'duplicate PO numbers', rows: db.prepare('SELECT po_number,COUNT(*) count FROM purchase_orders GROUP BY po_number HAVING count>1').all() },
  { name: 'duplicate GRN numbers', rows: db.prepare('SELECT grn_number,COUNT(*) count FROM grns GROUP BY grn_number HAVING count>1').all() },
  { name: 'duplicate active employee codes', rows: db.prepare('SELECT lower(employee_code) employee_code,COUNT(*) count FROM employees WHERE deleted_at IS NULL GROUP BY lower(employee_code) HAVING count>1').all() },
  { name: 'duplicate active item codes', rows: db.prepare('SELECT lower(item_code) item_code,COUNT(*) count FROM items WHERE deleted_at IS NULL GROUP BY lower(item_code) HAVING count>1').all() },
  { name: 'duplicate active supplier codes', rows: db.prepare('SELECT lower(supplier_code) supplier_code,COUNT(*) count FROM suppliers WHERE deleted_at IS NULL GROUP BY lower(supplier_code) HAVING count>1').all() },
  { name: 'invalid PR quantities', rows: db.prepare('SELECT id,pr_id,item_id,quantity FROM pr_items WHERE quantity<=0').all() },
  { name: 'invalid PO quantities or prices', rows: db.prepare('SELECT id,po_id,item_id,quantity,price,tax FROM po_items WHERE quantity<=0 OR price<0 OR tax<0').all() },
  { name: 'PO total mismatches', rows: db.prepare(`SELECT po.id,po.po_number,po.total_amount,ROUND(COALESCE(SUM(pi.quantity*pi.price*(1+pi.tax/100.0)),0),2) calculated FROM purchase_orders po LEFT JOIN po_items pi ON pi.po_id=po.id GROUP BY po.id HAVING ABS(po.total_amount-calculated)>.011`).all() },
  { name: 'fully received POs not closed', rows: db.prepare(`SELECT po.id,po.po_number,po.status FROM purchase_orders po WHERE po.status IN ('Approved','Printed') AND EXISTS(SELECT 1 FROM po_items WHERE po_id=po.id) AND NOT EXISTS(SELECT 1 FROM po_items pi WHERE pi.po_id=po.id AND COALESCE((SELECT SUM(gi.accepted_qty) FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.po_id=po.id AND gi.item_id=pi.item_id),0)<pi.quantity-.0001)`).all() },
  { name: 'active system-enabled employees without active login', rows: db.prepare(`SELECT e.id,e.employee_code,e.name FROM employees e LEFT JOIN users u ON u.employee_id=e.id AND u.deleted_at IS NULL AND u.is_active=1 WHERE e.deleted_at IS NULL AND e.status='Active' AND COALESCE(e.system_access_yn,1)=1 GROUP BY e.id HAVING COUNT(u.id)=0`).all() },
  { name: 'active warehouse users without warehouse', rows: db.prepare(`SELECT u.id,u.username,u.role FROM users u WHERE u.deleted_at IS NULL AND u.is_active=1 AND u.role IN ('WarehouseManager','WarehouseSupervisor','Storekeeper') AND u.warehouse_id IS NULL AND NOT EXISTS(SELECT 1 FROM employee_warehouse_assignments a WHERE a.employee_id=u.employee_id AND a.all_warehouses_yn=1 AND a.active_yn=1)`).all() },
  { name: 'active login role mismatches', rows: db.prepare(`SELECT u.id,u.username,u.role login_role,e.approval_role employee_role FROM users u JOIN employees e ON e.id=u.employee_id WHERE u.deleted_at IS NULL AND u.is_active=1 AND u.role<>e.approval_role`).all() },
  { name: 'primary warehouse/login mismatches', rows: db.prepare(`SELECT u.id,u.username,u.warehouse_id login_warehouse,e.warehouse_id employee_warehouse FROM users u JOIN employees e ON e.id=u.employee_id WHERE u.deleted_at IS NULL AND u.is_active=1 AND u.warehouse_id IS NOT e.warehouse_id`).all() },
  { name: 'unparsed inventory dates', rows: db.prepare(`SELECT id,expiry_date,received_date FROM inventory_layers WHERE expiry_date GLOB '[0-9]*.[0-9]*' OR received_date GLOB '[0-9]*.[0-9]*'`).all() },
  { name: 'duplicate employee calendar dates', rows: db.prepare(`SELECT employee_id,calendar_date,COUNT(*) count FROM employee_work_calendar GROUP BY employee_id,calendar_date HAVING count>1`).all() },
  { name: 'employees scheduled while unavailable', rows: db.prepare(`SELECT c.id,c.employee_id,c.calendar_date,a.availability_status FROM employee_work_calendar c JOIN employee_availability a ON a.employee_id=c.employee_id AND c.calendar_date BETWEEN a.date_from AND a.date_to WHERE c.day_type IN ('WORKDAY','HOLIDAY_WORKING') AND a.availability_status<>'Available'`).all() },
  { name: 'invalid calendar statuses', rows: db.prepare(`SELECT id,status FROM employee_work_calendar WHERE status NOT IN ('DRAFT','PROVISIONAL','PUBLISHED','LOCKED')`).all() },
  { name: 'manual calendar changes without protected history', rows: db.prepare(`SELECT c.id,c.employee_id,c.calendar_date FROM employee_work_calendar c LEFT JOIN calendar_overrides o ON o.calendar_entry_id=c.id WHERE c.manual_override_yn=1 GROUP BY c.id HAVING COUNT(o.id)=0`).all() },
  { name: 'invalid PO currencies', rows: db.prepare(`SELECT po.id,po.po_number,po.transaction_currency,po.base_currency FROM purchase_orders po LEFT JOIN currencies tc ON tc.currency_code=po.transaction_currency LEFT JOIN currencies bc ON bc.currency_code=po.base_currency WHERE (po.transaction_currency IS NOT NULL AND tc.id IS NULL) OR (po.base_currency IS NOT NULL AND bc.id IS NULL) OR COALESCE(po.exchange_rate,1)<=0`).all() },
  { name: 'PO base-currency conversion mismatches', rows: db.prepare(`SELECT id,po_number,total_amount,exchange_rate,base_currency_amount FROM purchase_orders WHERE base_currency_amount IS NOT NULL AND ABS(base_currency_amount-ROUND(total_amount*exchange_rate,2))>.011`).all() },
  { name: 'invalid invoice currencies', rows: db.prepare(`SELECT inv.id,inv.invoice_number,inv.transaction_currency,inv.base_currency FROM invoices inv LEFT JOIN currencies tc ON tc.currency_code=inv.transaction_currency LEFT JOIN currencies bc ON bc.currency_code=inv.base_currency WHERE (inv.transaction_currency IS NOT NULL AND tc.id IS NULL) OR (inv.base_currency IS NOT NULL AND bc.id IS NULL) OR COALESCE(inv.exchange_rate,1)<=0`).all() },
  { name: 'external handoff packages with source-document mismatch', rows: db.prepare(`SELECT id,invoice_number,finance_pack_reference FROM invoices WHERE finance_pack_status='Ready for Finance - External Process' AND COALESCE(source_documents_match,1)<>1`).all() },
  { name: 'reconciled invoices with a remaining difference', rows: db.prepare(`SELECT inv.id,inv.invoice_number,inv.adjusted_invoice_total,po.total_amount FROM invoices inv JOIN purchase_orders po ON po.id=inv.po_id WHERE inv.reconciliation_classification='Reconciled' AND ABS(COALESCE(inv.adjusted_invoice_total,inv.invoice_total)-po.total_amount)>.011`).all() },
  { name: 'accepted invoice variances without controlled reason', rows: db.prepare(`SELECT id,invoice_number FROM invoices WHERE variance_accepted_by IS NOT NULL AND (reconciliation_reason_code IS NULL OR trim(COALESCE(variance_acceptance_note,''))='')`).all() },
  { name: 'external handoff reconciliations without evidence', rows: db.prepare(`SELECT inv.id,inv.invoice_number FROM invoices inv WHERE inv.finance_pack_status='Ready for Finance - External Process' AND (inv.reconciliation_classification='Reconciled' OR inv.adjustment_manual_override=1 OR inv.variance_accepted_by IS NOT NULL) AND NOT EXISTS(SELECT 1 FROM document_attachments da WHERE da.document_type='INVOICE' AND da.document_id=inv.id)`).all() },
  { name: 'helpers with application access', rows: db.prepare(`SELECT e.id,e.employee_code,e.name,u.username FROM employees e LEFT JOIN users u ON u.employee_id=e.id AND u.deleted_at IS NULL AND u.is_active=1 WHERE e.approval_role='Helper' AND (COALESCE(e.system_access_yn,0)<>0 OR u.id IS NOT NULL)`).all() },
  { name: 'active helpers missing warehouse or supervisor', rows: db.prepare(`SELECT id,employee_code,name,warehouse_id,reports_to_employee_id FROM employees WHERE approval_role='Helper' AND status='Active' AND deleted_at IS NULL AND (warehouse_id IS NULL OR reports_to_employee_id IS NULL)`).all() },
  { name: 'helper supervisor warehouse mismatches', rows: db.prepare(`SELECT h.id,h.employee_code,h.warehouse_id helper_warehouse,s.warehouse_id supervisor_warehouse FROM employees h JOIN employees s ON s.id=h.reports_to_employee_id WHERE h.approval_role='Helper' AND h.warehouse_id<>s.warehouse_id`).all() },
  { name: 'calendar warehouse assignment mismatches', rows: db.prepare(`SELECT c.id,c.employee_id,c.warehouse_id,e.warehouse_id employee_warehouse FROM employee_work_calendar c JOIN employees e ON e.id=c.employee_id JOIN departments d ON d.id=c.department_id WHERE lower(d.name)='warehouse' AND c.warehouse_id IS NOT e.warehouse_id`).all() },
  { name: 'warehouse employees without an active scope', rows: db.prepare(`SELECT e.id,e.employee_code,e.name,e.approval_role FROM employees e WHERE e.deleted_at IS NULL AND e.status='Active' AND e.approval_role IN ('WarehouseManager','WarehouseSupervisor','Storekeeper','Helper') AND NOT EXISTS(SELECT 1 FROM employee_warehouse_assignments a WHERE a.employee_id=e.id AND a.active_yn=1 AND date('now') BETWEEN a.effective_from AND COALESCE(a.effective_to,'9999-12-31'))`).all() },
  { name: 'multiple primary warehouse assignments', rows: db.prepare(`SELECT employee_id,COUNT(*) count FROM employee_warehouse_assignments WHERE active_yn=1 AND primary_warehouse_yn=1 GROUP BY employee_id HAVING count>1`).all() },
  { name: 'single-site roles with invalid warehouse scope', rows: db.prepare(`SELECT e.id,e.employee_code,e.approval_role,COUNT(a.id) assignments,MAX(a.all_warehouses_yn) all_scope FROM employees e LEFT JOIN employee_warehouse_assignments a ON a.employee_id=e.id AND a.active_yn=1 WHERE e.deleted_at IS NULL AND e.status='Active' AND e.approval_role IN ('Storekeeper','Helper') GROUP BY e.id HAVING assignments<>1 OR all_scope=1`).all() },
  { name: 'employee city-country mismatches', rows: db.prepare(`SELECT e.id,e.employee_code,e.country_code,c.country_code city_country FROM employees e JOIN cities c ON c.id=e.city_id WHERE e.country_code<>c.country_code`).all() },
  { name: 'warehouse city-country mismatches', rows: db.prepare(`SELECT w.id,w.warehouse_code,w.country_code,c.country_code city_country FROM warehouses w JOIN cities c ON c.id=w.city_id WHERE w.country_code<>c.country_code`).all() },
  { name: 'company city-country mismatches', rows: db.prepare(`SELECT co.id,co.country_code,c.country_code city_country FROM company co JOIN cities c ON c.id=co.city_id WHERE co.country_code<>c.country_code`).all() },
  { name: 'invalid duplicate review pairs', rows: db.prepare(`SELECT id,primary_item_id,possible_duplicate_item_id,replacement_item_id FROM item_duplicate_reviews WHERE primary_item_id=possible_duplicate_item_id OR replacement_item_id IN(primary_item_id,possible_duplicate_item_id)`).all() },
  { name: 'disabled duplicate items without replacement', rows: db.prepare(`SELECT id,item_code,duplicate_status FROM items WHERE deleted_at IS NULL AND active_yn=0 AND duplicate_status IN('Merged','Disabled') AND replacement_item_id IS NULL`).all() },
];
const integrity = db.pragma('integrity_check') as Array<{ integrity_check: string }>;
const failed = checks.filter((check) => check.rows.length > 0);
console.log(JSON.stringify({ checked_at: new Date().toISOString(), integrity, checks: checks.map((c) => ({ name: c.name, findings: c.rows.length, rows: c.rows })) }, null, 2));
if (integrity.some((row) => row.integrity_check !== 'ok') || failed.length) process.exitCode = 1;
