import { Router } from 'express';
import db from '../db';
import { requireAuth,AuthedRequest } from '../middleware/auth';
import { requireRole } from '../middleware/rbac';
import { logAudit } from '../utils/auditLog';

const router=Router();
router.use(requireAuth,requireRole('SupplyChainManager'));

router.get('/ledger-dispositions',(_req,res)=>res.json(db.prepare(`SELECT l.*,i.item_code,i.description,w.name warehouse_name,loc.code bin_code,ru.full_name reviewed_by_name,au.full_name approved_by_name FROM legacy_ledger_reconciliation l JOIN items i ON i.id=l.item_id JOIN warehouses w ON w.id=l.warehouse_id LEFT JOIN locations loc ON loc.id=l.location_id LEFT JOIN users ru ON ru.id=l.reviewed_by LEFT JOIN users au ON au.id=l.approved_by ORDER BY l.id`).all()));
router.put('/ledger-dispositions/:id/review',(req:AuthedRequest,res)=>{
  const before=db.prepare('SELECT * FROM legacy_ledger_reconciliation WHERE id=?').get(req.params.id) as any;if(!before)return res.status(404).json({error:'Reconciliation warning not found'});
  const {management_decision,business_explanation,supporting_evidence,evidence_reference,financial_impact,inventory_impact,audit_reference}=req.body||{};
  const allowed=['APPROVED LEGACY OPENING BALANCE','CONTROLLED CORRECTION REQUIRED','INSUFFICIENT EVIDENCE','NOT APPLICABLE / FALSE POSITIVE','OTHER MANAGEMENT-APPROVED DISPOSITION'];
  if(!allowed.includes(management_decision))return res.status(400).json({error:'Select a permitted management disposition'});
  if(!String(business_explanation||'').trim())return res.status(400).json({error:'Business explanation is required'});
  db.prepare(`UPDATE legacy_ledger_reconciliation SET management_decision=?,business_explanation=?,supporting_evidence=?,evidence_reference=?,financial_impact=?,inventory_impact=?,audit_reference=?,reviewed_by=?,reviewed_at=datetime('now'),resolution_status='UNDER INVESTIGATION',updated_at=datetime('now') WHERE id=?`).run(management_decision,business_explanation,supporting_evidence||null,evidence_reference||null,financial_impact||null,inventory_impact||null,audit_reference||null,req.user!.id,before.id);
  logAudit('legacy_ledger_reconciliation',before.id,'UPDATE',req.user!.id,before,req.body);res.json({success:true,status:'REVIEWED - AWAITING APPROVAL'});
});
router.put('/ledger-dispositions/:id/approve',(req:AuthedRequest,res)=>{
  const before=db.prepare('SELECT * FROM legacy_ledger_reconciliation WHERE id=?').get(req.params.id) as any;if(!before)return res.status(404).json({error:'Reconciliation warning not found'});
  if(!before.reviewed_by||!before.management_decision||before.approved_by)return res.status(409).json({error:'The warning must be reviewed before approval'});
  if(Number(before.reviewed_by)===req.user!.id)return res.status(409).json({error:'The reviewer cannot approve their own ledger disposition'});
  const status=before.management_decision==='APPROVED LEGACY OPENING BALANCE'?'APPROVED LEGACY EXCEPTION':before.management_decision==='CONTROLLED CORRECTION REQUIRED'?'CONTROLLED ADJUSTMENT REQUIRED':before.management_decision==='NOT APPLICABLE / FALSE POSITIVE'?'RESOLVED':'UNDER INVESTIGATION';
  db.prepare(`UPDATE legacy_ledger_reconciliation SET approved_by=?,approved_at=datetime('now'),resolution_status=?,updated_at=datetime('now') WHERE id=?`).run(req.user!.id,status,before.id);
  logAudit('legacy_ledger_reconciliation',before.id,'APPROVE',req.user!.id,before,{management_decision:before.management_decision});res.json({success:true,status:'APPROVED'});
});

router.get('/ledger-batches',(_req,res)=>res.json(db.prepare(`SELECT b.*,COUNT(i.id) warning_count FROM legacy_ledger_disposition_batches b LEFT JOIN legacy_ledger_batch_items i ON i.batch_id=b.id GROUP BY b.id ORDER BY b.id DESC`).all()));
router.post('/ledger-batches',(req:AuthedRequest,res)=>{const {batch_reference,warning_ids,common_root_cause,common_evidence,evidence_reference,management_decision,business_explanation,audit_reference}=req.body||{},allowed=['APPROVED LEGACY OPENING BALANCE','CONTROLLED CORRECTION REQUIRED','INSUFFICIENT EVIDENCE','FALSE POSITIVE','OTHER MANAGEMENT-APPROVED DISPOSITION'];if(!String(batch_reference||'').trim()||!Array.isArray(warning_ids)||!warning_ids.length||![common_root_cause,common_evidence,evidence_reference,business_explanation,audit_reference].every(v=>String(v||'').trim())||!allowed.includes(management_decision))return res.status(400).json({error:'Complete batch evidence and decision are required'});const unique=Array.from(new Set(warning_ids.map(Number)));if(unique.some(id=>!db.prepare('SELECT 1 FROM legacy_ledger_reconciliation WHERE id=? AND approved_by IS NULL').get(id)))return res.status(409).json({error:'Every warning must exist and remain unapproved'});const id=db.transaction(()=>{const result=db.prepare('INSERT INTO legacy_ledger_disposition_batches(batch_reference,common_root_cause,common_evidence,evidence_reference,management_decision,business_explanation,audit_reference,reviewed_by) VALUES(?,?,?,?,?,?,?,?)').run(String(batch_reference).trim(),common_root_cause,common_evidence,evidence_reference,management_decision,business_explanation,audit_reference,req.user!.id);const batchId=Number(result.lastInsertRowid),insert=db.prepare('INSERT INTO legacy_ledger_batch_items(batch_id,warning_id) VALUES(?,?)');unique.forEach(warningId=>insert.run(batchId,warningId));logAudit('legacy_ledger_disposition_batches',batchId,'CREATE',req.user!.id,undefined,{warning_ids:unique});return batchId;}).immediate();res.status(201).json({id,status:'AWAITING APPROVAL',warning_count:unique.length});});
router.put('/ledger-batches/:id/approve',(req:AuthedRequest,res)=>{const batch=db.prepare("SELECT * FROM legacy_ledger_disposition_batches WHERE id=? AND status='AWAITING APPROVAL'").get(req.params.id)as any;if(!batch)return res.status(404).json({error:'Pending batch not found'});if(Number(batch.reviewed_by)===req.user!.id)return res.status(409).json({error:'Reviewer cannot approve the same batch'});const ids=(db.prepare('SELECT warning_id FROM legacy_ledger_batch_items WHERE batch_id=?').all(batch.id)as any[]).map(x=>x.warning_id),status=batch.management_decision==='APPROVED LEGACY OPENING BALANCE'?'APPROVED LEGACY EXCEPTION':batch.management_decision==='CONTROLLED CORRECTION REQUIRED'?'CONTROLLED ADJUSTMENT REQUIRED':batch.management_decision==='FALSE POSITIVE'?'RESOLVED':'UNDER INVESTIGATION';try{db.transaction(()=>{const update=db.prepare(`UPDATE legacy_ledger_reconciliation SET root_cause_classification=?,supporting_evidence=?,evidence_reference=?,management_decision=?,business_explanation=?,audit_reference=?,reviewed_by=?,reviewed_at=?,approved_by=?,approved_at=datetime('now'),resolution_status=?,updated_at=datetime('now') WHERE id=? AND approved_by IS NULL`);ids.forEach(id=>{if(!update.run(batch.common_root_cause,batch.common_evidence,batch.evidence_reference,batch.management_decision,batch.business_explanation,batch.audit_reference,batch.reviewed_by,batch.reviewed_at,req.user!.id,status,id).changes)throw Object.assign(new Error(`Warning ${id} already approved`),{status:409});});db.prepare("UPDATE legacy_ledger_disposition_batches SET status='APPROVED',approved_by=?,approved_at=datetime('now') WHERE id=?").run(req.user!.id,batch.id);logAudit('legacy_ledger_disposition_batches',batch.id,'APPROVE',req.user!.id,batch,{warning_ids:ids});}).immediate();}catch(e:any){return res.status(e.status||409).json({error:e.message});}res.json({success:true,warning_count:ids.length});});
router.get('/sod-reviews',(_req,res)=>res.json(db.prepare(`SELECT s.*,u.full_name,e.employee_code,e.name employee_name FROM sod_conflict_reviews s JOIN users u ON u.id=s.user_id LEFT JOIN employees e ON e.id=s.employee_id ORDER BY s.risk DESC,s.id`).all()));
router.put('/sod-reviews/:id',(req:AuthedRequest,res)=>{const before=db.prepare('SELECT * FROM sod_conflict_reviews WHERE id=?').get(req.params.id) as any;if(!before)return res.status(404).json({error:'SoD conflict not found'});const {management_decision,business_justification,permission_change,compensating_control,expiry_date}=req.body||{};const allowed=['PERMISSION REMOVED','PERMISSION REDUCED','APPROVED BUSINESS EXCEPTION','FALSE POSITIVE','ROLE REDESIGN REQUIRED'];if(!allowed.includes(management_decision))return res.status(400).json({error:'Select a permitted SoD decision'});if(!String(business_justification||'').trim())return res.status(400).json({error:'Business need/justification is required'});if(management_decision==='APPROVED BUSINESS EXCEPTION'&&(!String(compensating_control||'').trim()||!expiry_date))return res.status(400).json({error:'Approved exceptions require a compensating control and expiry date'});db.prepare(`UPDATE sod_conflict_reviews SET management_decision=?,business_justification=?,permission_change=?,compensating_control=?,review_date=date('now'),expiry_date=?,status='REQUIRES MANAGEMENT REVIEW',updated_at=datetime('now') WHERE id=?`).run(management_decision,business_justification,permission_change||null,compensating_control||null,expiry_date||null,before.id);logAudit('sod_conflict_reviews',before.id,'UPDATE',req.user!.id,before,req.body);res.json({success:true});});
router.put('/sod-reviews/:id/approve',(req:AuthedRequest,res)=>{const before=db.prepare('SELECT * FROM sod_conflict_reviews WHERE id=?').get(req.params.id) as any;if(!before)return res.status(404).json({error:'SoD conflict not found'});if(!before.management_decision)return res.status(409).json({error:'A documented decision is required first'});const status=before.management_decision==='APPROVED BUSINESS EXCEPTION'?'APPROVED BUSINESS EXCEPTION':before.management_decision==='FALSE POSITIVE'?'FALSE POSITIVE':'TRUE CONFLICT';db.prepare(`UPDATE sod_conflict_reviews SET approved_by=?,approval_date=date('now'),status=?,updated_at=datetime('now') WHERE id=?`).run(req.user!.id,status,before.id);logAudit('sod_conflict_reviews',before.id,'APPROVE',req.user!.id,before,{decision:before.management_decision});res.json({success:true});});

router.get('/accounting-periods',(_req,res)=>res.json(db.prepare('SELECT * FROM accounting_periods ORDER BY start_date DESC').all()));
router.post('/accounting-periods',(req:AuthedRequest,res)=>{const {fiscal_year,period_number,start_date,end_date,status='OPEN',reason,approval_reference}=req.body||{};if(!fiscal_year||!period_number||!/^\d{4}-\d{2}-\d{2}$/.test(start_date)||!/^\d{4}-\d{2}-\d{2}$/.test(end_date)||start_date>end_date)return res.status(400).json({error:'Fiscal year, period number, and a valid date range are required'});if(db.prepare('SELECT 1 FROM accounting_periods WHERE start_date<=? AND end_date>=?').get(end_date,start_date))return res.status(409).json({error:'Accounting periods cannot overlap'});const row=db.prepare('INSERT INTO accounting_periods(fiscal_year,period_number,start_date,end_date,status,reason,approval_reference) VALUES(?,?,?,?,?,?,?)').run(fiscal_year,period_number,start_date,end_date,status,reason||null,approval_reference||null);logAudit('accounting_periods',Number(row.lastInsertRowid),'CREATE',req.user!.id,undefined,req.body);res.status(201).json({id:Number(row.lastInsertRowid)});});
router.put('/accounting-periods/:id/status',(req:AuthedRequest,res)=>{const before=db.prepare('SELECT * FROM accounting_periods WHERE id=?').get(req.params.id) as any;if(!before)return res.status(404).json({error:'Accounting period not found'});const {status,reason,approval_reference}=req.body||{};if(!['OPEN','SOFT CLOSED','CLOSED'].includes(status)||!String(reason||'').trim())return res.status(400).json({error:'Valid status and documented reason are required'});const reopen=status==='OPEN'&&before.status!=='OPEN';db.prepare(`UPDATE accounting_periods SET status=?,reason=?,approval_reference=?,closed_by=CASE WHEN ?='OPEN' THEN closed_by ELSE ? END,closed_at=CASE WHEN ?='OPEN' THEN closed_at ELSE datetime('now') END,reopened_by=CASE WHEN ? THEN ? ELSE reopened_by END,reopened_at=CASE WHEN ? THEN datetime('now') ELSE reopened_at END WHERE id=?`).run(status,reason,approval_reference||null,status,req.user!.id,status,reopen?1:0,req.user!.id,reopen?1:0,before.id);logAudit('accounting_periods',before.id,'UPDATE',req.user!.id,before,req.body);res.json({success:true});});
router.get('/document-revisions',(_req,res)=>res.json(db.prepare('SELECT * FROM document_revisions ORDER BY created_at DESC,id DESC').all()));

router.get('/authorization-limits',(_req,res)=>res.json({po:db.prepare(`SELECT e.id employee_id,e.employee_code,e.name,e.approval_role,e.approval_limit,c.base_currency currency FROM employees e CROSS JOIN (SELECT COALESCE(base_currency,currency,'SAR') base_currency FROM company WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 1)c WHERE e.deleted_at IS NULL AND e.approval_role IN('PurchaseOfficer','PurchaseManager','SupplyChainManager') ORDER BY e.name`).all(),material_issue:db.prepare(`SELECT l.*,e.employee_code,e.name employee_name,w.name warehouse_name,u.full_name approved_by_name FROM material_issue_authorization_limits l JOIN employees e ON e.id=l.employee_id LEFT JOIN warehouses w ON w.id=l.warehouse_id JOIN users u ON u.id=l.approved_by ORDER BY l.id DESC`).all()}));
router.post('/authorization-limits/po',(req:AuthedRequest,res)=>{const {employee_id,approval_limit,currency,effective_from,expiry_date}=req.body||{},employee=db.prepare("SELECT * FROM employees WHERE id=? AND deleted_at IS NULL AND status='Active' AND approval_role IN('PurchaseOfficer','PurchaseManager','SupplyChainManager')").get(employee_id)as any;if(!employee||!Number.isFinite(Number(approval_limit))||Number(approval_limit)<0)return res.status(400).json({error:'Active procurement approver and non-negative limit are required'});const base=String((db.prepare("SELECT COALESCE(base_currency,currency,'SAR') currency FROM company WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 1").get()as any)?.currency||'SAR');if(String(currency||base)!==base)return res.status(400).json({error:`Approval limits must be recorded in base currency ${base}`});db.transaction(()=>{db.prepare('UPDATE employees SET approval_limit=? WHERE id=?').run(approval_limit,employee.id);db.prepare("UPDATE approval_limit_history SET status='SUPERSEDED' WHERE employee_id=? AND approval_type='PO' AND status='ACTIVE'").run(employee.id);const row=db.prepare("INSERT INTO approval_limit_history(employee_id,approval_type,old_limit,new_limit,currency,effective_from,expiry_date,approved_by) VALUES(?,'PO',?,?,?,?,?,?)").run(employee.id,employee.approval_limit,approval_limit,base,effective_from||new Date().toISOString().slice(0,10),expiry_date||null,req.user!.id);logAudit('approval_limit_history',Number(row.lastInsertRowid),'CREATE',req.user!.id,{old_limit:employee.approval_limit},{new_limit:approval_limit,currency:base});}).immediate();res.json({success:true});});
router.post('/authorization-limits/material-issue',(req:AuthedRequest,res)=>{const {employee_id,warehouse_id,value_limit,currency,quantity_limit,category_scope,effective_from,expiry_date}=req.body||{},employee=db.prepare("SELECT * FROM employees WHERE id=? AND deleted_at IS NULL AND status='Active' AND approval_role IN('Storekeeper','WarehouseSupervisor','WarehouseManager')").get(employee_id)as any;if(!employee||!Number.isFinite(Number(value_limit))||Number(value_limit)<0)return res.status(400).json({error:'Active warehouse employee and non-negative value limit are required'});if(warehouse_id&&!db.prepare('SELECT 1 FROM employee_warehouse_assignments WHERE employee_id=? AND warehouse_id=? AND active_yn=1').get(employee_id,warehouse_id))return res.status(409).json({error:'Limit warehouse must be actively assigned to the employee'});const base=String((db.prepare("SELECT COALESCE(base_currency,currency,'SAR') currency FROM company WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 1").get()as any)?.currency||'SAR');if(String(currency||base)!==base)return res.status(400).json({error:`Issue limits must be recorded in base currency ${base}`});const row=db.prepare('INSERT INTO material_issue_authorization_limits(employee_id,warehouse_id,value_limit,currency,quantity_limit,category_scope,effective_from,expiry_date,approved_by) VALUES(?,?,?,?,?,?,?,?,?)').run(employee_id,warehouse_id||null,value_limit,base,quantity_limit||null,category_scope||null,effective_from||new Date().toISOString().slice(0,10),expiry_date||null,req.user!.id);logAudit('material_issue_authorization_limits',Number(row.lastInsertRowid),'CREATE',req.user!.id,undefined,req.body);res.status(201).json({id:Number(row.lastInsertRowid)});});

export default router;
