import { useEffect, useMemo, useState } from "react";
import client from "../../api/client";
import DataTable from "../../components/DataTable";
import Modal from "../../components/Modal";
import { useAuth } from "../../contexts/AuthContext";

const parentTypes={Zone:[],Aisle:["Zone"],Rack:["Zone","Aisle"],Shelf:["Rack"],Bin:["Zone","Aisle","Rack","Shelf"]};
const DAY_NAMES=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const blankWarehouse={name:"",site_type:"Factory",site_name:"",address:"",country_code:"",city_id:"",postal_code:"",region_province:"",time_zone:"Asia/Riyadh",operation_24h_yn:0,shifts_enabled_yn:1,operating_days:[0,1,2,3,4,5,6],operating_start_time:"03:00",operating_end_time:"03:00"};

export default function WarehousesPage(){
  const {user}=useAuth(),canDeactivate=user?.role==="SupplyChainManager";
  const [warehouses,setWarehouses]=useState([]),[locations,setLocations]=useState([]),[reports,setReports]=useState([]),[readiness,setReadiness]=useState(null),[reportDetail,setReportDetail]=useState(null),[shiftPreview,setShiftPreview]=useState(null),[deactivationReason,setDeactivationReason]=useState(""),[showWh,setShowWh]=useState(false),[showLoc,setShowLoc]=useState(false),[warehouseForm,setWarehouseForm]=useState(blankWarehouse),[locForm,setLocForm]=useState({type:"Zone",label:""}),[error,setError]=useState(""),[reference,setReference]=useState({countries:[],cities:[]}),[timeZones,setTimeZones]=useState([]),[procurement,setProcurement]=useState({shifts_enabled_yn:0,operating_start_time:"08:00",operating_end_time:"17:00",operating_days:[0,1,2,3,4]});
  const load=()=>Promise.all([client.get("/masters/warehouses"),client.get("/masters/locations"),canDeactivate?client.get("/masters/warehouses/deactivation-reports"):Promise.resolve({data:[]})]).then(([w,l,r])=>{setWarehouses(w.data);setLocations(l.data);setReports(r.data);setError("");}).catch(e=>setError(e.response?.data?.error||"Unable to load warehouses and storage locations"));
  useEffect(()=>{load();client.get("/workforce/reference").then(r=>{setReference(r.data);if(r.data.shift_mode?.procurement)setProcurement(r.data.shift_mode.procurement);}).catch(()=>undefined);client.get("/masters/time-zones").then(r=>setTimeZones(r.data)).catch(()=>undefined);},[]);
  const parents=useMemo(()=>locations.filter(l=>Number(l.warehouse_id)===Number(locForm.warehouse_id)&&parentTypes[locForm.type]?.includes(l.type)),[locations,locForm]);
  async function saveWarehouse(){try{if(warehouseForm.id){const changed=warehouseForm.operating_start_time!==warehouseForm.original_operating_start_time||warehouseForm.operating_end_time!==warehouseForm.original_operating_end_time;if(changed){const preview=await client.post(`/masters/warehouses/${warehouseForm.id}/shift-design-preview`,warehouseForm);setShiftPreview(preview.data);return;}await client.put(`/masters/warehouses/${warehouseForm.id}`,warehouseForm);}else await client.post("/masters/warehouses",warehouseForm);setShowWh(false);setWarehouseForm(blankWarehouse);setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to save warehouse");}}
  async function confirmShiftDesign(){try{await client.put(`/masters/warehouses/${warehouseForm.id}`,{...warehouseForm,confirm_shift_design:true});setShiftPreview(null);setShowWh(false);setWarehouseForm(blankWarehouse);setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to confirm the automatic shift design");}}
  async function saveLocation(){try{if(locForm.id)await client.put(`/masters/locations/${locForm.id}`,locForm);else await client.post("/masters/locations",locForm);setShowLoc(false);setLocForm({type:"Zone",label:""});setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to save location");}}
  async function saveProcurementMode(){try{const r=await client.put("/workforce/shift-mode/procurement",procurement);setProcurement(r.data.procurement);setError("");}catch(e){setError(e.response?.data?.error||"Unable to update procurement shift mode");}}
  async function inspectDeactivation(row){try{const r=await client.get(`/masters/warehouses/${row.id}/deactivation-readiness`);setReadiness(r.data);setDeactivationReason("");setError("");}catch(e){setError(e.response?.data?.error||"Unable to inspect warehouse deactivation readiness");}}
  async function deactivateWarehouse(){try{const r=await client.post(`/masters/warehouses/${readiness.warehouse.id}/deactivate`,{reason:deactivationReason});setReadiness(null);setDeactivationReason("");setError("");await load();const detail=await client.get(`/masters/warehouses/deactivation-reports/${r.data.report_id}`);setReportDetail(detail.data);}catch(e){setError(e.response?.data?.error||"Warehouse deactivation failed");}}
  async function viewReport(id){try{const r=await client.get(`/masters/warehouses/deactivation-reports/${id}`);setReportDetail(r.data);setError("");}catch(e){setError(e.response?.data?.error||"Unable to load deactivation report");}}
  const field=(label,key,type="text")=><label className="block text-sm font-medium">{label}<input type={type} className="input mt-1" value={warehouseForm[key]??""} onChange={e=>setWarehouseForm({...warehouseForm,[key]:e.target.value})}/></label>;
  return <div>
    <div className="mb-4"><h1 className="text-xl font-semibold text-slate-900">Warehouse Sites & Storage Locations</h1><p className="text-sm text-slate-500">Warehouse operating hours control its own continuous shift schedule and employee calendar.</p></div>
    {error&&!showWh&&!showLoc&&<div className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="space-y-6">
      <div className="card p-4"><div className="mb-3"><h2 className="font-medium">Procurement Operating Schedule</h2><p className="text-xs text-slate-500">Use configured rotating shifts only when procurement works in shifts. Otherwise, all procurement employees follow one standard operating-hours shift.</p></div><div className="grid gap-3 md:grid-cols-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!procurement.shifts_enabled_yn} onChange={e=>setProcurement({...procurement,shifts_enabled_yn:e.target.checked?1:0})}/>Enable procurement shifts</label><label className="text-sm font-medium">Operating Start<input className="input mt-1" type="time" value={procurement.operating_start_time} onChange={e=>setProcurement({...procurement,operating_start_time:e.target.value})}/></label><label className="text-sm font-medium">Operating End<input className="input mt-1" type="time" value={procurement.operating_end_time} onChange={e=>setProcurement({...procurement,operating_end_time:e.target.value})}/></label><div className="flex items-end"><button className="btn-primary w-full" onClick={saveProcurementMode}>Save Schedule Mode</button></div></div><div className="mt-3 flex flex-wrap gap-2">{DAY_NAMES.map((name,day)=><label key={name} className="flex items-center gap-2 rounded-lg bg-slate-50 px-2 py-1.5 text-xs"><input type="checkbox" checked={(procurement.operating_days||[]).includes(day)} onChange={e=>setProcurement({...procurement,operating_days:e.target.checked?[...(procurement.operating_days||[]),day]:(procurement.operating_days||[]).filter(value=>value!==day)})}/>{name}</label>)}</div></div>
      <div className="card p-4"><div className="mb-3 flex justify-between"><h2 className="font-medium">Warehouse Sites</h2><button className="btn-secondary text-xs" onClick={()=>{setError("");setWarehouseForm(blankWarehouse);setShowWh(true);}}>+ Add Warehouse</button></div>
        <DataTable rows={warehouses} columns={[{key:"warehouse_code",label:"Code"},{key:"name",label:"Warehouse"},{key:"time_zone",label:"Time Zone"},{key:"operating_start_time",label:"Opens"},{key:"operating_end_time",label:"Closes"},{key:"shifts_enabled_yn",label:"Schedule",render:v=>v?"Multiple shifts":"Standard hours"},{key:"site_type",label:"Site Type"},{key:"city",label:"City"}]} actions={row=><div className="flex gap-2"><button className="btn-secondary text-xs" onClick={()=>{setError("");setWarehouseForm({...row,operating_days:row.operating_days||[],original_operating_start_time:row.operating_start_time,original_operating_end_time:row.operating_end_time});setShowWh(true);}}>Edit Warehouse</button>{canDeactivate&&<button className="rounded-lg border border-rose-200 px-2 py-1 text-xs font-medium text-rose-700 hover:bg-rose-50" onClick={()=>inspectDeactivation(row)}>Deactivate</button>}</div>}/>
      </div>
      {canDeactivate&&<div className="card p-4"><div className="mb-3"><h2 className="font-medium">Warehouse Deactivation Reports</h2><p className="text-xs text-slate-500">Permanent audit snapshots retained after warehouse deactivation.</p></div><DataTable rows={reports} columns={[{key:"report_number",label:"Report"},{key:"warehouse_code",label:"Code"},{key:"warehouse_name",label:"Warehouse"},{key:"deactivated_at",label:"Deactivated"},{key:"deactivated_by_name",label:"Deactivated By"},{key:"stock_quantity",label:"Final Stock"},{key:"fifo_quantity",label:"Final FIFO"}]} actions={row=><button className="btn-secondary text-xs" onClick={()=>viewReport(row.id)}>View Report</button>}/></div>}
      <div className="card p-4"><div className="mb-3 flex justify-between"><h2 className="font-medium">Generated Storage IDs</h2><button className="btn-secondary text-xs" onClick={()=>{setError("");setLocForm({type:"Zone",label:""});setShowLoc(true);}}>+ Add Location</button></div>
        <DataTable rows={locations} columns={[{key:"warehouse_name",label:"Warehouse"},{key:"site_name",label:"Site"},{key:"type",label:"Level"},{key:"code",label:"Physical ID"},{key:"label",label:"Description"},{key:"parent_code",label:"Parent"},{key:"location_type",label:"Storage Type"},{key:"status",label:"Status"}]} actions={row=><button className="btn-secondary text-xs" onClick={()=>{setError("");setLocForm({...row});setShowLoc(true);}}>Edit</button>}/>
      </div>
    </div>
    {showWh&&<Modal title={warehouseForm.id?"Edit Warehouse Site":"New Warehouse Site"} onClose={()=>setShowWh(false)}>
      <div className="compact-form">
        {field("Warehouse Name","name")}
        <label className="block text-sm font-medium">Site Type<select className="input mt-1" value={warehouseForm.site_type} onChange={e=>setWarehouseForm({...warehouseForm,site_type:e.target.value})}>{["Factory","Construction Site","Distribution Center","Project Site","Office","Other"].map(x=><option key={x}>{x}</option>)}</select></label>
        {field("Facility / Project / Site Name","site_name")}
        <div className="md:col-span-2 rounded-xl border border-indigo-200 bg-indigo-50 p-3 space-y-3"><div className="font-semibold text-indigo-950">Warehouse Operating Calendar</div><label className="block text-sm font-medium">IANA Time Zone<select className="input mt-1" required value={warehouseForm.time_zone||""} onChange={e=>setWarehouseForm({...warehouseForm,time_zone:e.target.value})}><option value="">Select time zone...</option>{timeZones.map(zone=><option key={zone}>{zone}</option>)}</select></label><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!warehouseForm.operation_24h_yn} onChange={e=>setWarehouseForm({...warehouseForm,operation_24h_yn:e.target.checked?1:0,operating_start_time:e.target.checked?"00:00":warehouseForm.operating_start_time,operating_end_time:e.target.checked?"00:00":warehouseForm.operating_end_time})}/>24-hour operation</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!warehouseForm.shifts_enabled_yn} onChange={e=>setWarehouseForm({...warehouseForm,shifts_enabled_yn:e.target.checked?1:0})}/>Enable multiple warehouse shifts</label></div><div className="grid grid-cols-2 gap-3">{field("Operating Start","operating_start_time","time")}{field("Operating End","operating_end_time","time")}</div><div><div className="mb-1 text-xs font-semibold uppercase tracking-wide text-indigo-700">Applicable operating days</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{DAY_NAMES.map((name,day)=><label key={name} className="flex items-center gap-2 rounded-lg bg-white px-2 py-1.5 text-xs"><input type="checkbox" checked={(warehouseForm.operating_days||[]).includes(day)} onChange={e=>setWarehouseForm({...warehouseForm,operating_days:e.target.checked?[...(warehouseForm.operating_days||[]),day]:(warehouseForm.operating_days||[]).filter(value=>value!==day)})}/>{name}</label>)}</div></div><p className="text-xs text-indigo-700">When multiple shifts are disabled, employees follow one standard shift covering these operating hours. Saved multi-shift templates are retained for later reactivation.</p></div>
        <label className="block text-sm font-medium md:col-span-2">Physical Address<textarea className="input mt-1" value={warehouseForm.address||""} onChange={e=>setWarehouseForm({...warehouseForm,address:e.target.value})}/></label>
        <label className="block text-sm font-medium">Country<select className="input mt-1" value={warehouseForm.country_code||""} onChange={e=>setWarehouseForm({...warehouseForm,country_code:e.target.value,city_id:""})}><option value="">Select...</option>{reference.countries.map(c=><option key={c.country_code} value={c.country_code}>{c.country_name}</option>)}</select></label>
        <label className="block text-sm font-medium">City<select className="input mt-1" value={warehouseForm.city_id||""} onChange={e=>setWarehouseForm({...warehouseForm,city_id:Number(e.target.value)})}><option value="">Select...</option>{reference.cities.filter(c=>c.country_code===warehouseForm.country_code).map(c=><option key={c.id} value={c.id}>{c.city_name}</option>)}</select></label>
        {field("Region / Province","region_province")}{field("Postal Code","postal_code")}
        {error&&<p className="text-sm text-rose-600 md:col-span-2">{error}</p>}
        <div className="flex justify-end gap-2 md:col-span-2"><button className="btn-secondary" onClick={()=>setShowWh(false)}>Cancel</button><button className="btn-primary" onClick={saveWarehouse}>{warehouseForm.id?"Save Warehouse":"Create Warehouse"}</button></div>
      </div>
    </Modal>}
    {shiftPreview&&<Modal wide title={`Confirm Automatic Shift Design — ${shiftPreview.warehouse_name}`} onClose={()=>setShiftPreview(null)}><div className="space-y-4"><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm text-indigo-950"><strong>Proposed operating window:</strong> {shiftPreview.operating_start_time}–{shiftPreview.operating_end_time}<br/><span>{shiftPreview.shifts_enabled_yn?`${shiftPreview.proposed_shifts.length} shift(s) automatically calculated on standard 30-minute start intervals, with at least two hours between each next start and the previous scheduled end.`:"One standard operating-hours shift will be used because multiple shifts are disabled."}</span></div><div className="overflow-x-auto"><table className="table-base"><thead><tr><th>Shift</th><th>Start</th><th>Scheduled End</th><th>Working Time</th><th>Break</th><th>Scheduled Total</th></tr></thead><tbody>{shiftPreview.proposed_shifts.map(row=><tr key={row.sequence}><td>{row.shift_label||`Shift ${row.sequence}`}</td><td>{row.start_time}</td><td>{row.end_time}</td><td>{(row.working_minutes/60).toFixed(2)} hr</td><td>{row.break_minutes} min</td><td>{(row.scheduled_minutes/60).toFixed(2)} hr</td></tr>)}</tbody></table></div><div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">The existing operating times and active schedule remain unchanged until you confirm. Future automatic calendar entries will use the confirmed design.</div>{error&&<p className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShiftPreview(null)}>Continue Editing</button><button className="btn-primary" onClick={confirmShiftDesign}>Confirm Operating Times & Shift Design</button></div></div></Modal>}
    {readiness&&<Modal wide title={`Deactivate ${readiness.warehouse.name}`} onClose={()=>setReadiness(null)}><div className="space-y-4"><div className={`rounded-xl border p-4 ${readiness.ready?"border-emerald-200 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><h4 className="font-semibold">{readiness.ready?"Warehouse is ready for controlled deactivation":`${readiness.open_task_count} open task(s) must be resolved`}</h4><p className="mt-1 text-sm">Stock: {readiness.stock_quantity} · FIFO: {readiness.fifo_quantity}. Deactivation creates and permanently retains stock, GRN, issue, return, transfer, adjustment, cycle-count, tool and ledger reports.</p></div>{readiness.open_tasks.map(task=><section key={task.category} className="rounded-xl border border-slate-200 p-3"><h4 className="font-semibold text-rose-700">{task.category} ({task.count})</h4><div className="mt-2 overflow-x-auto"><table className="table-base"><thead><tr>{Object.keys(task.records[0]||{}).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{task.records.map((record,index)=><tr key={index}>{Object.keys(task.records[0]||{}).map(key=><td key={key}>{String(record[key]??"—")}</td>)}</tr>)}</tbody></table></div></section>)}{readiness.ready&&<div><label className="block text-sm font-medium">Deactivation Reason<textarea className="input mt-1" value={deactivationReason} onChange={e=>setDeactivationReason(e.target.value)} placeholder="Explain why this warehouse is being deactivated"/></label><button className="mt-3 rounded-lg bg-rose-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={deactivationReason.trim().length<5} onClick={deactivateWarehouse}>Confirm Deactivation & Generate Reports</button></div>}{error&&<p className="text-sm text-rose-600">{error}</p>}</div></Modal>}
    {reportDetail&&<Modal wide title={`Warehouse Deactivation Report ${reportDetail.report_number}`} onClose={()=>setReportDetail(null)}><div className="space-y-4"><div className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-3"><div><strong>Warehouse</strong><br/>{reportDetail.warehouse_code} — {reportDetail.warehouse_name}</div><div><strong>Deactivated</strong><br/>{reportDetail.deactivated_at} by {reportDetail.deactivated_by_name}</div><div><strong>Reason</strong><br/>{reportDetail.deactivation_reason}</div></div>{Object.entries(reportDetail.snapshot?.reports||{}).map(([name,rows])=><section key={name} className="rounded-xl border border-slate-200 p-3"><h4 className="font-semibold capitalize">{name.replaceAll("_"," ")} ({rows.length})</h4>{rows.length>0?<div className="mt-2 max-h-72 overflow-auto"><table className="table-base"><thead><tr>{Object.keys(rows[0]).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{Object.keys(rows[0]).map(key=><td key={key}>{String(row[key]??"—")}</td>)}</tr>)}</tbody></table></div>:<p className="mt-1 text-xs text-slate-500">No records at the time of deactivation.</p>}</section>)}</div></Modal>}
    {showLoc&&<Modal title={locForm.id?`Edit Storage Location ${locForm.code}`:"New Physical Storage Location"} onClose={()=>setShowLoc(false)}><div className="space-y-3">
      <label className="block text-sm font-medium">Warehouse Site<select disabled={!!locForm.id} className="input mt-1" value={locForm.warehouse_id||""} onChange={e=>setLocForm({...locForm,warehouse_id:Number(e.target.value),parent_id:null})}><option value="">Select...</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.warehouse_code} — {w.name}</option>)}</select></label>
      <label className="block text-sm font-medium">Storage Level<select disabled={!!locForm.id} className="input mt-1" value={locForm.type} onChange={e=>setLocForm({...locForm,type:e.target.value,parent_id:null})}>{Object.keys(parentTypes).map(x=><option key={x}>{x}</option>)}</select></label>
      {locForm.type!=="Zone"&&<label className="block text-sm font-medium">Parent Location<select disabled={!!locForm.id} className="input mt-1" value={locForm.parent_id||""} onChange={e=>setLocForm({...locForm,parent_id:Number(e.target.value)})}><option value="">Select...</option>{parents.map(p=><option key={p.id} value={p.id}>{p.code}{p.label?` — ${p.label}`:""}</option>)}</select></label>}
      {locForm.type!=="Zone"&&locForm.warehouse_id&&!parents.length&&!locForm.id&&<div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">No valid parent exists in this warehouse. Create the required parent level first—for example, create a Zone before adding an Aisle or Rack.</div>}
      <label className="block text-sm font-medium">Description / Physical Label<input className="input mt-1" value={locForm.label||""} onChange={e=>setLocForm({...locForm,label:e.target.value})}/></label>
      {locForm.type==="Bin"&&<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">BIN Type<select className="input mt-1" value={locForm.location_type||"Standard BIN"} onChange={e=>setLocForm({...locForm,location_type:e.target.value})}>{["Standard BIN","Pallet Location","Bulk Storage","Tool Storage","Quarantine","Inspection","Rejected Material","Damaged Material","Return Area","Receiving Area","Staging Area","Outdoor Yard","Chemical Storage","Floor Storage","Bay","Tank","Silo"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Status<select className="input mt-1" value={locForm.status||"Available"} onChange={e=>setLocForm({...locForm,status:e.target.value})}>{["Available","Partially Available","Full","Blocked","Under Inspection","Maintenance","Quarantine","Inactive"].map(x=><option key={x}>{x}</option>)}</select></label></div>}
      {error&&<p className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShowLoc(false)}>Cancel</button><button className="btn-primary" onClick={saveLocation}>{locForm.id?"Save Location":"Generate Location ID"}</button></div>
    </div></Modal>}
  </div>;
}
