import { PRODUCT_BRAND } from './brand';

export const DOCUMENT_THEME = Object.freeze({
  product: PRODUCT_BRAND.name,
  tagline: PRODUCT_BRAND.tagline,
  poweredBy: `Powered by ${PRODUCT_BRAND.name}`,
  generatedBy: `Generated by ${PRODUCT_BRAND.name}`,
  logo: PRODUCT_BRAND.logo,
  colors: Object.freeze({
    navy: '#052f5f',
    blue: '#075fa8',
    teal: '#0796a5',
    green: '#16843a',
    white: '#ffffff',
    background: '#f2f7fa',
    border: '#c8dbe5',
    text: '#202b33',
    muted: '#526671',
  }),
});

export function drawPdfBrandFooter(pdf, { pageWidth, pageHeight, margin, footerTop, pageLabel, copyLabel }) {
  const { colors } = DOCUMENT_THEME;
  pdf.setDrawColor(5, 47, 95);
  pdf.setLineWidth(.45);
  pdf.line(margin, footerTop + 3, pageWidth - margin, footerTop + 3);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(32, 43, 51);
  pdf.text(DOCUMENT_THEME.poweredBy, margin, footerTop + 8);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6.5);
  pdf.setTextColor(82, 102, 113);
  pdf.text(DOCUMENT_THEME.tagline, margin, footerTop + 12);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(7);
  pdf.setTextColor(7, 82, 156);
  pdf.text(pageLabel, pageWidth - margin, footerTop + 8, { align: 'right' });
  if (copyLabel) {
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(82, 102, 113);
    pdf.text(copyLabel, pageWidth - margin, footerTop + 12, { align: 'right' });
  }
  pdf.setTextColor(0, 0, 0);
}
