import React, { useEffect, useMemo, useState } from 'react';
import client from '../../api/client';
import { useAuth } from '../../contexts/AuthContext';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { formatCurrency } from '../../utils/currency';
import { CompanyContact, CompanyLogo } from '../../components/Branding';
import { downloadElementPdf } from '../../utils/downloadPdf';
import { formatRole } from '../../utils/roles';

const CURRENCY_COLUMNS=new Set(['value','freight','price_variance','tax_amount','approval_limit']);
const QUANTITY_COLUMNS=new Set(['quantity','total_quantity','ordered_quantity','received_quantity','accepted_quantity','rejected_quantity','quantity_received','accepted_qty','rejected_qty','current_quantity','quantity_change','outstanding_quantity','received','accepted','rejected','po_count','supplier_count','active_suppliers','active_employees','submitted_prs','pending_po_approvals','open_purchase_orders','low_stock_items','expiry_risk_layers','invoice_match_exceptions','suppliers_invited','quotations_received','lines','accurate_lines','supporting_documents']);
const isCurrency=(key:string)=>CURRENCY_COLUMNS.has(key)||/(_amount|_value|_price|_cost|_spend|_total)$/.test(key);
const isPercentage=(key:string)=>key==='tax'||key==='variance_percent'||/(_percent|_pct|_percentage)$/.test(key);
const isTotal=(key:string)=>(isCurrency(key)&&!/(unit_price|unit_cost|average_price|comparison_price|previous_supplier_price|price_variance|standard_cost|avg_unit_cost)$/.test(key))||QUANTITY_COLUMNS.has(key);
const label=(key:string)=>key.replace(/_/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase()).replace(/ Po\b/g,' PO').replace(/ Pr\b/g,' PR').replace(/ Grn\b/g,' GRN').replace(/ Rfq\b/g,' RFQ').replace(/ Uom\b/g,' UOM').replace(/ Pct\b/g,'%');
function value(row:any,key:string){const raw=row[key];if(raw==null||raw==='')return '—';if(isCurrency(key))return formatCurrency(raw,row.currency||undefined);if(isPercentage(key)){const n=Number(raw);return `${Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:2}):raw}%`;}if(/(^|_)role$/.test(key))return formatRole(String(raw));if(typeof raw==='number')return raw.toLocaleString(undefined,{maximumFractionDigits:2});return String(raw);}
function dateLike(row:any){const entry=Object.entries(row).find(([key])=>key.includes('date')||key==='day'||key==='month');return entry?.[1]?String(entry[1]):'';}
function escapeHtml(input:unknown){return String(input??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
function safeSpreadsheetCell(input:unknown){const text=String(input??'');return escapeHtml(/^[=+\-@]/.test(text)?`'${text}`:text);}

const ROLES={proc:['SupplyChainManager','PurchaseManager','PurchaseOfficer'],stock:['SupplyChainManager','WarehouseManager','WarehouseSupervisor','Storekeeper']};
const REPORTS=[
 {key:'invoice-register',label:'Invoice Register',group:'Procurement',roles:ROLES.proc},
 {key:'po-vs-grn',label:'PO vs GRN',group:'Procurement',roles:ROLES.proc},
 {key:'po-vs-invoice',label:'PO vs Invoice',group:'Procurement',roles:ROLES.proc},
 {key:'grn-vs-invoice',label:'GRN vs Invoice',group:'Procurement',roles:ROLES.proc},
 {key:'three-way-match',label:'Three-Way Match',group:'Procurement',roles:ROLES.proc},
 {key:'bin-stock',label:'Bin Stock',group:'Inventory',roles:ROLES.stock},
 {key:'pr-register',label:'Purchase Requisition Register',group:'Procurement',roles:ROLES.proc},{key:'rfq-status',label:'RFQ Status',group:'Procurement',roles:ROLES.proc},{key:'quotation-comparison',label:'Quotation Comparison',group:'Procurement',roles:ROLES.proc},{key:'po-register',label:'Purchase Order Register',group:'Procurement',roles:ROLES.proc},{key:'open-po',label:'Open Purchase Orders',group:'Procurement',roles:ROLES.proc},{key:'po-delivery-performance',label:'PO Delivery Performance',group:'Procurement',roles:ROLES.proc},{key:'purchase-summary',label:'Daily Purchase Summary',group:'Procurement',roles:ROLES.proc},{key:'supplier-purchase-analysis',label:'Supplier Purchase Analysis',group:'Procurement',roles:ROLES.proc},{key:'po-aging',label:'Purchase Order Aging',group:'Procurement',roles:ROLES.proc},{key:'price-variance',label:'Price Variance Detail',group:'Procurement',roles:ROLES.proc},{key:'finance-payment-verification',label:'Finance Payment Verification',group:'Procurement',roles:ROLES.proc},
 {key:'stock-balance',label:'Stock Balance',group:'Inventory',roles:ROLES.stock},{key:'fifo-valuation',label:'FIFO Inventory Valuation',group:'Inventory',roles:ROLES.stock},{key:'low-stock',label:'Low Stock',group:'Inventory',roles:ROLES.stock},{key:'batch-report',label:'Batch and Expiry Stock',group:'Inventory',roles:ROLES.stock},{key:'cycle-count-accuracy',label:'Cycle Count Accuracy',group:'Inventory',roles:ROLES.stock},
 {key:'grn-register',label:'Goods Receipt Register',group:'Warehouse',roles:ROLES.stock},{key:'daily-receiving',label:'Supplier / PO Receiving (GRN)',group:'Warehouse',roles:ROLES.stock},{key:'daily-issues',label:'Daily Material Issues',group:'Warehouse',roles:ROLES.stock},{key:'returns-report',label:'Material Returns',group:'Warehouse',roles:ROLES.stock},{key:'transfers-report',label:'Warehouse Transfer Dispatch & Status',group:'Warehouse',roles:ROLES.stock},{key:'transfer-receipts-report',label:'Inter-Warehouse Transfer Receipts',group:'Warehouse',roles:ROLES.stock},{key:'adjustments-report',label:'Stock Adjustments',group:'Warehouse',roles:ROLES.stock},{key:'stock-ledger',label:'Permanent Stock Ledger',group:'Warehouse',roles:ROLES.stock},
 {key:'consumption-by-employee',label:'Consumption by Employee',group:'Employee Accountability',roles:ROLES.stock},{key:'consumption-by-department',label:'Consumption by Department',group:'Employee Accountability',roles:ROLES.stock},{key:'outstanding-returnables',label:'Outstanding Returnables',group:'Employee Accountability',roles:ROLES.stock},{key:'tool-condition',label:'Damaged, Lost and Repair Tools',group:'Tools',roles:ROLES.stock},
 {key:'user-activity-log',label:'User Activity Log',group:'System Administration',roles:['SupplyChainManager']},
 {key:'employee-permissions',label:'Employee Permissions Register',group:'System Administration',roles:['SupplyChainManager']},
 {key:'system-integrity-summary',label:'System Integrity Check',group:'System Administration',roles:['SupplyChainManager']},
 {key:'inventory-integrity',label:'Inventory Integrity',group:'System Administration',roles:['SupplyChainManager']},
 {key:'duplicate-master-data',label:'Duplicate Master Data',group:'System Administration',roles:['SupplyChainManager']},
 {key:'segregation-of-duties',label:'Segregation of Duties Conflicts',group:'System Administration',roles:['SupplyChainManager']},
 {key:'audit-control-center',label:'Audit & Control Center',group:'System Administration',roles:['SupplyChainManager']},
 {key:'legacy-ledger-reconciliation',label:'Legacy Ledger Reconciliation Register',group:'System Administration',roles:['SupplyChainManager']},
 {key:'warehouse-access-verification',label:'Warehouse Access Verification',group:'System Administration',roles:['SupplyChainManager']},
 {key:'audit-finding-closure',label:'Audit Finding Closure Register',group:'System Administration',roles:['SupplyChainManager']},
 {key:'backup-restore-history',label:'Backup & Restore History',group:'System Administration',roles:['SupplyChainManager']},
 {key:'employee-workday',label:'Employee Workday Report',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'employee-schedule',label:'Employee Individual Schedule',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'combined-30-day-roster',label:'Combined 30-Day Roster',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'department-shift-roster',label:'Department Shift Roster',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'employee-shift-distribution',label:'Employee Shift Distribution & Fairness',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'shift-coverage',label:'Shift Coverage',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'understaffed-shifts',label:'Understaffed Shifts',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'uncovered-roles',label:'Uncovered Roles',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'employee-availability',label:'Employee Availability',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'availability-conflicts',label:'Availability Conflicts',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'holiday-calendar',label:'Holiday Calendar',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'holiday-working',label:'Holiday Working',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'calendar-adjustments',label:'Calendar Adjustments',group:'Employee & Shift',roles:['SupplyChainManager']},
 {key:'helper-assignments',label:'Helper Assignment Report',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'helper-shift-distribution',label:'Helper Shift Distribution',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'availability-impact',label:'Employee Availability Impact',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'calendar-regeneration',label:'Calendar Regeneration Audit',group:'Employee & Shift',roles:['SupplyChainManager']},{key:'calendar-download-audit',label:'Calendar Print & Download Audit',group:'Employee & Shift',roles:['SupplyChainManager']},
 {key:'country-master',label:'Country Master',group:'Country & Currency',roles:['SupplyChainManager']},{key:'currency-master',label:'Currency Master',group:'Country & Currency',roles:['SupplyChainManager']},{key:'exchange-rate-master',label:'Exchange Rate Master',group:'Country & Currency',roles:['SupplyChainManager']},
 {key:'duplicate-item-analysis',label:'Duplicate Item Analysis',group:'Master Data',roles:['SupplyChainManager','PurchaseManager','WarehouseManager']},
 {key:'executive-supply-chain-overview',label:'Executive Supply Chain Overview',group:'Executive Reports',roles:['SupplyChainManager']},{key:'open-po-commitments',label:'Open PO Commitments',group:'Executive Reports',roles:['SupplyChainManager']},{key:'approval-governance',label:'Approval Governance & Turnaround',group:'Executive Reports',roles:['SupplyChainManager']},
 {key:'purchase-by-category',label:'Purchase by Category',group:'Executive Reports',roles:['SupplyChainManager']},{key:'purchase-by-month',label:'Purchase by Month',group:'Executive Reports',roles:['SupplyChainManager']},
 {key:'inventory-aging',label:'Inventory Aging & Exposure',group:'Executive Reports',roles:['SupplyChainManager']},{key:'location-stock-executive',label:'Warehouse Location Stock',group:'Executive Reports',roles:['SupplyChainManager']},
 {key:'supplier-performance-executive',label:'Supplier Performance Executive',group:'Executive Reports',roles:['SupplyChainManager']},
];
const PURPOSE:Record<string,string>={Procurement:'Provides management visibility over purchasing demand, sourcing, commitments, supplier performance, value and exceptions.',Inventory:'Presents current stock health, valuation, control accuracy and inventory risk requiring management attention.',Warehouse:'Provides an auditable view of receipts, issues, movements, adjustments and permanent stock transactions.', 'Employee Accountability':'Supports material custody, consumption accountability and outstanding returnable follow-up.',Tools:'Highlights controlled tools requiring investigation, recovery, repair or maintenance action.','System Administration':'Provides a controlled management record of authenticated user navigation, operational presence, and application workspaces accessed.','Executive Reports':'Consolidates enterprise-level procurement, supplier, approval, commitment, inventory exposure, aging, and warehouse-location intelligence for executive decision-making.'};

export default function ReportsPage(){
 const {user}=useAuth();const navigate=useNavigate();const [params,setParams]=useSearchParams();const reportPermission=(group:string)=>group==='Procurement'?'report.procurement':group==='Inventory'?'report.inventory':group==='Warehouse'?'report.warehouse':group==='Employee Accountability'?'report.employee':group==='Tools'?'report.tools':group==='System Administration'?'report.system':['Executive Reports','Employee & Shift','Country & Currency'].includes(group)?'report.executive':'';const available=REPORTS.filter(r=>user&&r.roles.includes(user.role)&&(!reportPermission(r.group)||!user.permission_keys||user.permission_keys.includes(reportPermission(r.group))));const [active,setActive]=useState('');const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [company,setCompany]=useState<any>({});const [generatedAt,setGeneratedAt]=useState(new Date());const [filters,setFilters]=useState({from:'',to:'',warehouse:'',department:'',supplier:''});
 useEffect(()=>{client.get('/settings/company').then(r=>setCompany(r.data)).catch(()=>undefined);},[]);
 useEffect(()=>{const requested=params.get('report');if(requested&&available.some(r=>r.key===requested)&&requested!==active){setActive(requested);return;}if(!active&&available[0])setActive(available[0].key);},[params,user?.role,active]);
 useEffect(()=>{if(!active)return;setLoading(true);setError('');client.get(`/reports/${active}`).then(r=>{setRows(r.data);setGeneratedAt(new Date());}).catch((e)=>{setRows([]);setError(e?.response?.data?.error||'Unable to load report');}).finally(()=>setLoading(false));},[active]);
 const report=available.find(r=>r.key===active);const groups=Array.from(new Set(available.map(r=>r.group)));const group=report?.group||groups[0]||'';const departmentReports=available.filter(r=>r.group===group);
 const filtered=useMemo(()=>rows.filter(row=>{const date=dateLike(row);const contains=(needle:string,keys:string[])=>!needle||keys.some(k=>String(row[k]??'').toLowerCase().includes(needle.toLowerCase()));return(!filters.from||!date||date>=filters.from)&&(!filters.to||!date||date<=filters.to)&&contains(filters.warehouse,['warehouse_name','warehouse','from_warehouse_name','to_warehouse_name'])&&contains(filters.department,['department_name','department'])&&contains(filters.supplier,['supplier_name','name','supplier']);}),[rows,filters]);
 const columns=rows.length?Object.keys(rows[0]):[];const currencies=new Set(filtered.map(r=>r.currency).filter(Boolean));const totals=Object.fromEntries(columns.map(key=>[key,isTotal(key)&&(!isCurrency(key)||currencies.size<=1)?filtered.reduce((s,r)=>s+(Number(r[key])||0),0):null]));
 const firstMoney=columns.find(k=>totals[k]!=null&&isCurrency(k));const firstQty=columns.find(k=>totals[k]!=null&&!isCurrency(k));const dimensionKey=columns.find(k=>/supplier_name|warehouse_name|employee_name|department_name/.test(k));const unique=dimensionKey?new Set(filtered.map(r=>r[dimensionKey]).filter(Boolean)).size:0;
 const filterText=[filters.from&&`From ${filters.from}`,filters.to&&`To ${filters.to}`,filters.warehouse&&`Warehouse: ${filters.warehouse}`,filters.department&&`Department: ${filters.department}`,filters.supplier&&`Supplier: ${filters.supplier}`].filter(Boolean);
 function selectGroup(next:string){const first=available.find(r=>r.group===next);if(first){setActive(first.key);setParams({report:first.key});}}
 function exportExcel(){const title=report?.label||'Report';const headers=columns;const meta=`<table><tr><td colspan="${Math.max(headers.length,1)}"><h1>${escapeHtml(company.name||'Company')}</h1><h2>${escapeHtml(title)}</h2><p>ProcuraFlow Professional Edition | Generated by ${escapeHtml(user?.full_name||'')} | ${escapeHtml(generatedAt.toLocaleString())}</p><p>Filters: ${escapeHtml(filterText.join(' | ')||'All records')}</p></td></tr></table>`;const total=`<tr>${headers.map((h,i)=>`<td><strong>${safeSpreadsheetCell(totals[h]==null?(i===0?'TOTAL':''):value({...filtered[0],[h]:totals[h]},h))}</strong></td>`).join('')}</tr>`;const table=`<table border="1"><tr>${headers.map(h=>`<th>${escapeHtml(label(h))}</th>`).join('')}</tr>${filtered.map(r=>`<tr>${headers.map(h=>`<td>${safeSpreadsheetCell(value(r,h))}</td>`).join('')}</tr>`).join('')}${filtered.length?total:''}</table>`;const blob=new Blob([meta+table],{type:'application/vnd.ms-excel'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${active}-${new Date().toISOString().slice(0,10)}.xls`;a.click();URL.revokeObjectURL(url);}
 return <div><div className="mb-5 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Executive Reports</h1><p className="mt-1 text-sm text-slate-500">Controlled management reports with branded PDF and structured Excel output.</p></div><button type="button" className="btn-secondary print:hidden" onClick={()=>navigate(-1)}>Close</button></div>
  <section className="card mb-5 p-5 print:hidden"><div className="grid gap-4 lg:grid-cols-2"><label className="text-sm font-medium">Report Department<select className="input mt-1" value={group} onChange={e=>selectGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label className="text-sm font-medium">Report Name<select className="input mt-1" value={active} onChange={e=>{setActive(e.target.value);setParams({report:e.target.value});}}>{departmentReports.map(r=><option value={r.key} key={r.key}>{r.label}</option>)}</select></label></div><div className="mt-4 grid gap-3 md:grid-cols-5"><label className="text-xs font-medium">Date From<input className="input mt-1" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label className="text-xs font-medium">Date To<input className="input mt-1" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label className="text-xs font-medium">Warehouse<input className="input mt-1" placeholder="All warehouses" value={filters.warehouse} onChange={e=>setFilters({...filters,warehouse:e.target.value})}/></label><label className="text-xs font-medium">Department<input className="input mt-1" placeholder="All departments" value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})}/></label><label className="text-xs font-medium">Supplier<input className="input mt-1" placeholder="All suppliers" value={filters.supplier} onChange={e=>setFilters({...filters,supplier:e.target.value})}/></label></div><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setFilters({from:'',to:'',warehouse:'',department:'',supplier:''})}>Clear Filters</button><button className="btn-secondary" disabled={!filtered.length} onClick={exportExcel}>Export Excel</button><button className="btn-secondary" disabled={!filtered.length} onClick={()=>downloadElementPdf('report-print-document',`${active}-${new Date().toISOString().slice(0,10)}`,{orientation:'landscape'})}>Download PDF</button><button className="btn-primary" disabled={!filtered.length} onClick={()=>window.print()}>Print Report</button></div></section>
  <article id="report-print-document" className="controlled-print-document executive-report overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
   <header className="report-header"><div className="flex min-w-0 items-center gap-4">{company.logo_url?<CompanyLogo company={company} size="report"/>:<div className="report-logo-fallback">CO</div>}<div className="min-w-0"><div className="report-company">{company.name||'Company Name'}</div><div className="report-address">{company.address||'Company address not configured'}</div><CompanyContact company={company}/></div></div></header>
   <section className="report-title-band"><div><div className="report-classification">{group} · Management Information</div><h2>{report?.label||'Report'}</h2><p>{PURPOSE[group]||'Controlled operational management report.'}</p></div><div className="report-meta"><div><span>Generated</span><strong>{generatedAt.toLocaleDateString()} {generatedAt.toLocaleTimeString()}</strong></div><div><span>Generated By</span><strong>{user?.full_name||'—'}</strong></div><div><span>Fiscal Year</span><strong>{company.financial_year||'Not configured'}</strong></div></div></section>
   <section className="report-kpis"><div><span>Report Records</span><strong>{filtered.length.toLocaleString()}</strong><small>{filtered.length===rows.length?'Complete dataset':`${rows.length-filtered.length} filtered out`}</small></div>{firstMoney&&<div><span>{label(firstMoney)}</span><strong>{value({...filtered[0],[firstMoney]:totals[firstMoney]},firstMoney)}</strong><small>Report total</small></div>}{firstQty&&<div><span>{label(firstQty)}</span><strong>{Number(totals[firstQty]||0).toLocaleString(undefined,{maximumFractionDigits:2})}</strong><small>Report total</small></div>}<div><span>{dimensionKey?`Unique ${label(dimensionKey)}`:'Report Status'}</span><strong>{dimensionKey?unique:'Current'}</strong><small>As at generation time</small></div></section>
   <section className="report-filter-strip"><strong>Applied scope:</strong> {filterText.length?filterText.map(x=><span key={String(x)}>{x}</span>):<span>All available records</span>}</section>
   {error?<div className="p-8 text-center text-rose-700">{error}</div>:loading?<div className="p-8 text-center text-slate-500">Preparing report…</div>:!filtered.length?<div className="p-10 text-center"><div className="text-base font-semibold text-slate-700">No records found</div><div className="mt-1 text-sm text-slate-500">Adjust the report filters or confirm that transactions exist for this report.</div></div>:active==='audit-control-center'?<div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((row,i)=>{const tone=row.status==='PASS'?'border-emerald-300 bg-emerald-50 text-emerald-900':row.status==='FAIL'?'border-rose-300 bg-rose-50 text-rose-900':row.status==='WARNING'?'border-amber-300 bg-amber-50 text-amber-900':'border-slate-300 bg-slate-50 text-slate-700';const symbol=row.status==='PASS'?'●':row.status==='FAIL'?'●':row.status==='WARNING'?'●':'○';return <button type="button" key={i} className={`rounded-xl border p-4 text-left ${tone}`} onClick={()=>{if(row.report&&available.some(r=>r.key===row.report)){setActive(row.report);setParams({report:row.report});}}}><div className="flex items-start justify-between gap-3"><strong>{row.control}</strong><span>{symbol} {row.status}</span></div><div className="mt-3 text-2xl font-bold">{Number(row.findings||0).toLocaleString()}</div><div className="mt-1 text-xs">Outstanding findings · Select for supporting evidence</div></button>})}</div>:<div className="report-table-wrap"><table className="report-table"><thead><tr>{columns.map(k=><th key={k} className={isCurrency(k)||QUANTITY_COLUMNS.has(k)?'numeric':''}>{label(k)}</th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={i}>{columns.map(k=><td key={k} className={isCurrency(k)||typeof row[k]==='number'?'numeric':''}>{value(row,k)}</td>)}</tr>)}</tbody><tfoot><tr>{columns.map((k,i)=><td key={k} className={isCurrency(k)||QUANTITY_COLUMNS.has(k)?'numeric':''}>{totals[k]==null?(i===0?'REPORT TOTAL':''):value({...filtered[0],[k]:totals[k]},k)}</td>)}</tr></tfoot></table></div>}
   <footer className="report-footer"><div><div className="report-product">PROCURA<span>FLOW</span></div><div className="report-edition">Supply Chain Management System · Controlled live-data report</div></div><div>Confidential · Internal Management Use <span className="print-page-number ml-2"/></div></footer>
  </article>
  <div className="mt-5 flex justify-end print:hidden"><button type="button" className="btn-secondary" onClick={()=>navigate(-1)}>Close</button></div>
 </div>;
}
