import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { PRODUCT_BRAND } from '../config/brand';
import { DOCUMENT_THEME } from '../config/documentTheme';
export function ProductBrand({ compact = false, inverse = false }) { return _jsx("div", { className: `flex min-w-0 items-center ${inverse ? 'rounded-xl bg-white px-2 py-1 shadow-sm' : ''}`, children: _jsx("img", { src: PRODUCT_BRAND.logo, alt: `${PRODUCT_BRAND.name} — ${PRODUCT_BRAND.tagline}`, className: `${compact ? 'h-10 w-40' : 'h-20 w-80'} max-w-full object-contain object-left`, draggable: "false" }) }); }
export function CompanyLogo({ company, src, size = 'document', className = '' }) { const source = src || company?.logo_url; if (!source)
    return null; const sizes = { nav: 'h-8 w-12', compact: 'h-9 w-14', dashboard: 'h-14 w-14', document: 'h-20 w-28', report: 'h-16 w-24' }; return _jsx("img", { src: source, alt: `${company?.name || company?.company_name || 'Company'} logo`, className: `company-logo ${sizes[size]} shrink-0 object-contain ${className}` }); }
export function CompanyBrand({ company, compact = false, inverse = false }) { return _jsxs("div", { className: "flex min-w-0 items-center gap-3", children: [company?.logo_url ? _jsx(CompanyLogo, { company: company, size: compact ? 'compact' : 'report', className: "rounded bg-white p-1" }) : _jsx("div", { className: `${compact ? 'h-9 w-9' : 'h-16 w-16'} shrink-0 rounded-lg bg-white/10 flex items-center justify-center font-bold ${inverse ? 'text-white' : 'text-indigo-700'}`, children: String(company?.name || company?.company_name || 'C').charAt(0) }), _jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: `truncate font-semibold ${inverse ? 'text-white' : 'text-slate-900'}`, children: company?.name || company?.company_name || 'Company Name' }), !compact && company?.address && _jsx("div", { className: `text-xs whitespace-pre-line ${inverse ? 'text-slate-300' : 'text-slate-600'}`, children: company.address })] })] }); }
export function CompanyContact({ company }) { const contacts = [company?.phone, company?.email, company?.website].filter(Boolean); return _jsxs(_Fragment, { children: [contacts.length > 0 && _jsx("div", { className: "text-xs text-slate-600", children: contacts.join(' | ') }), (company?.tax_info || company?.registration_number) && _jsx("div", { className: "text-xs text-slate-600", children: [company.tax_info && `Tax/VAT: ${company.tax_info}`, company.registration_number && `Registration: ${company.registration_number}`].filter(Boolean).join(' | ') }), company?.branch_info && _jsxs("div", { className: "text-xs text-slate-600", children: ["Branch: ", company.branch_info] })] }); }
export function DocumentCompanyHeader({ company, title, reference, date, fiscalYear }) { return _jsxs("header", { className: "flex justify-between gap-6 border-b-2 border-indigo-700 pb-5", children: [_jsxs("div", { children: [_jsx(CompanyBrand, { company: company }), _jsx("div", { className: "ml-[92px] -mt-5", children: _jsx(CompanyContact, { company: company }) })] }), _jsxs("div", { className: "shrink-0 text-right", children: [_jsx("div", { className: "text-2xl font-bold tracking-wide text-indigo-950", children: title }), reference && _jsx("div", { className: "mt-2 text-sm font-semibold", children: reference }), date && _jsxs("div", { className: "text-xs text-slate-600", children: ["Date: ", date] }), _jsxs("div", { className: "text-xs text-slate-600", children: ["Fiscal Year: ", fiscalYear || company?.financial_year || 'Not configured'] })] })] }); }
export function GeneratedByFooter({ note }) { return _jsxs("footer", { className: "document-brand-footer print-avoid-break mt-8 border-t-2 pt-3 text-[10px]", children: [note && _jsx("div", { className: "mb-2 text-center", children: note }), _jsxs("div", { className: "flex items-center justify-between gap-4 rounded-md px-3 py-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("img", { src: DOCUMENT_THEME.logo, alt: "ProcuraFlow product logo", className: "h-8 w-32 object-contain object-left" }), _jsx("span", { className: "sr-only", children: DOCUMENT_THEME.poweredBy })] }), _jsxs("div", { className: "text-right", children: [_jsx("strong", { children: DOCUMENT_THEME.poweredBy }), _jsx("div", { children: DOCUMENT_THEME.tagline }), _jsx("span", { className: "print-page-number ml-3" })] })] })] }); }
