import { useEffect,useMemo,useState } from "react";
import client from "../api/client";
import Modal from "../components/Modal";
import SearchSelect from "../components/SearchSelect";

const SCOPE_LABELS={ALL_ASSIGNED_PROCUREMENT:"All Assigned Procurement Packages",ALL_AUTHORIZED_PROCUREMENT:"All Authorized Procurement Packages",PR:"Specific PR",RFQ:"Specific RFQ",PROCUREMENT_PACKAGE:"Specific Procurement Package",PO:"Specific PO",INVOICE:"Specific Invoice",ALL_ASSIGNED_WAREHOUSES:"All Assigned Warehouses",WAREHOUSE:"Specific Warehouse",GRN:"Specific GRN",MATERIAL_ISSUE:"Specific Material Issue",TRANSFER:"Specific Material Transfer",INVENTORY_ADJUSTMENT:"Specific Inventory Adjustment"};
const RECORD_LABELS={PR:"Purchase Requisition",RFQ:"RFQ",PROCUREMENT_PACKAGE:"Procurement Package",PO:"Purchase Order",INVOICE:"Invoice",WAREHOUSE:"Warehouse",GRN:"GRN",MATERIAL_ISSUE:"Material Issue",TRANSFER:"Transfer",INVENTORY_ADJUSTMENT:"Inventory Adjustment"};
const initial=()=>({delegate_employee_id:"",authority_code:"",scope_type:"",scope_id:"",effective_from:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),effective_until:"",reason_code:"",reason_other:"",business_justification:"",broad_scope_confirmed:false});
const displayDate=value=>value?new Date(value).toLocaleString():"—";

export default function DelegatedAuthorityPage(){
  const[rows,setRows]=useState([]),[employees,setEmployees]=useState([]),[catalog,setCatalog]=useState({authorities:[],reasons:[],broad_scopes:[]}),[options,setOptions]=useState([]),[form,setForm]=useState(initial()),[error,setError]=useState(""),[confirming,setConfirming]=useState(false),[revoking,setRevoking]=useState(null),[revocationReason,setRevocationReason]=useState(""),[extending,setExtending]=useState(null),[extension,setExtension]=useState({effective_until:"",reason:""}),[audit,setAudit]=useState(null),[statusFilter,setStatusFilter]=useState("All"),[departmentFilter,setDepartmentFilter]=useState("All"),[search,setSearch]=useState("");
  const load=()=>Promise.all([client.get("/delegations"),client.get("/delegations/eligible-employees"),client.get("/delegations/catalog")]).then(([a,b,c])=>{setRows(a.data);setEmployees(b.data);setCatalog(c.data);});
  useEffect(()=>{load().catch(e=>setError(e?.response?.data?.error||"Unable to load delegated authority controls"));},[]);
  const employee=employees.find(e=>Number(e.id)===Number(form.delegate_employee_id));
  const authorities=catalog.authorities.filter(a=>a.department===employee?.department);
  const authority=authorities.find(a=>a.code===form.authority_code);
  const broad=catalog.broad_scopes.includes(form.scope_type);
  useEffect(()=>{if(!form.scope_type||catalog.broad_scopes.includes(form.scope_type)){setOptions([]);return;}client.get("/delegations/scope-options",{params:{scope_type:form.scope_type}}).then(r=>setOptions(r.data.map(x=>({value:x.id,label:x.label})))).catch(()=>setOptions([]));},[form.scope_type,catalog.broad_scopes]);
  const complete=employee&&authority&&form.scope_type&&form.effective_from&&form.effective_until&&form.reason_code&&form.business_justification.trim().length>=10&&(!broad||form.broad_scope_confirmed)&&(broad||Number(form.scope_id))&&(form.reason_code!=="OTHER"||form.reason_other.trim().length>=3);
  const selectedScope=options.find(o=>Number(o.value)===Number(form.scope_id))?.label||SCOPE_LABELS[form.scope_type];
  const filtered=useMemo(()=>rows.filter(r=>(statusFilter==="All"||r.effective_status===statusFilter)&&(departmentFilter==="All"||r.department===departmentFilter)&&(!search.trim()||[r.delegate_name,r.employee_code,r.delegation_number,r.authority_label,r.scope_type,r.scope_id].join(" ").toLowerCase().includes(search.toLowerCase()))),[rows,statusFilter,departmentFilter,search]);
  function changeDelegate(value){setForm({...initial(),effective_from:form.effective_from,delegate_employee_id:Number(value)});}
  function changeAuthority(value){const next=authorities.find(a=>a.code===value);setForm({...form,authority_code:value,scope_type:next?.scopes?.[0]||"",scope_id:"",broad_scope_confirmed:false});}
  async function create(){try{setError("");await client.post("/delegations",{...form,scope_id:broad?null:Number(form.scope_id)});setConfirming(false);setForm(initial());await load();}catch(e){setConfirming(false);setError(e?.response?.data?.error||"Unable to create delegation");}}
  async function revoke(){try{setError("");await client.put(`/delegations/${revoking.id}/revoke`,{reason:revocationReason});setRevoking(null);setRevocationReason("");await load();}catch(e){setError(e?.response?.data?.error||"Unable to revoke delegation");}}
  async function extend(){try{setError("");await client.put(`/delegations/${extending.id}/extend`,extension);setExtending(null);setExtension({effective_until:"",reason:""});await load();}catch(e){setError(e?.response?.data?.error||"Unable to extend delegation");}}
  async function openAudit(){try{setAudit((await client.get('/delegations/audit')).data);}catch(e){setError(e?.response?.data?.error||'Unable to load delegation audit history');}}
  return <div>
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold text-slate-900">Delegated Authority</h1><p className="mt-1 max-w-5xl text-sm text-slate-600">Controlled temporary delegation for Procurement and Warehouse operational authority. Only the Supply Chain Manager can create or manage delegations. Delegation does not change an employee&apos;s normal role or grant unrelated permissions.</p></div><button className="btn-secondary" onClick={openAudit}>View Audit History</button></div>
    {error&&<div className="mb-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <section className="card mb-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-indigo-950">Create Controlled Delegation</h2><p className="text-xs text-slate-500">Maximum period: {catalog.maximum_days||30} days. Permanent role and normal warehouse assignments remain unchanged.</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">Supply Chain Manager only</span></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        <SearchSelect label="Eligible Delegate" value={form.delegate_employee_id} onChange={changeDelegate} placeholder="Search employee name or ID..." options={employees.map(e=>({value:e.id,label:`${e.employee_code} — ${e.name} (${e.role_label})`}))}/>
        <label className="text-sm font-medium text-slate-700">Department<input className="input mt-1 bg-slate-50" readOnly value={employee?.department||"Select an employee"}/></label>
        <label className="text-sm font-medium text-slate-700">Normal Role<input className="input mt-1 bg-slate-50" readOnly value={employee?.role_label||"Select an employee"}/></label>
        <label className="text-sm font-medium text-slate-700">Delegated Authority<select className="input mt-1" value={form.authority_code} disabled={!employee} onChange={e=>changeAuthority(e.target.value)}><option value="">Select authority...</option>{authorities.map(a=><option key={a.code} value={a.code}>{a.label}</option>)}</select></label>
        <label className="text-sm font-medium text-slate-700">Scope<select className="input mt-1" value={form.scope_type} disabled={!authority} onChange={e=>setForm({...form,scope_type:e.target.value,scope_id:"",broad_scope_confirmed:false})}><option value="">Select scope...</option>{authority?.scopes.map(s=><option key={s} value={s}>{SCOPE_LABELS[s]||s}</option>)}</select></label>
        {form.scope_type&&!broad&&<SearchSelect label={RECORD_LABELS[form.scope_type]||"Scope Record"} value={form.scope_id} onChange={value=>setForm({...form,scope_id:Number(value)})} placeholder={`Search ${RECORD_LABELS[form.scope_type]||"record"}...`} options={options}/>} 
        <label className="text-sm font-medium text-slate-700">Effective From<input type="datetime-local" className="input mt-1" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label>
        <label className="text-sm font-medium text-slate-700">Effective Until<input type="datetime-local" className="input mt-1" value={form.effective_until} onChange={e=>setForm({...form,effective_until:e.target.value})}/></label>
        <label className="text-sm font-medium text-slate-700">Reason<select className="input mt-1" value={form.reason_code} onChange={e=>setForm({...form,reason_code:e.target.value})}><option value="">Select reason...</option>{catalog.reasons.map(r=><option key={r.code} value={r.code}>{r.label}</option>)}</select></label>
        {form.reason_code==="OTHER"&&<label className="text-sm font-medium text-slate-700">Other Reason<input className="input mt-1" value={form.reason_other} onChange={e=>setForm({...form,reason_other:e.target.value})}/></label>}
        <label className="text-sm font-medium text-slate-700 md:col-span-2 xl:col-span-3">Business Justification<textarea className="input mt-1 min-h-24" value={form.business_justification} onChange={e=>setForm({...form,business_justification:e.target.value})} placeholder="Explain why the temporary delegation is necessary..."/></label>
      </div>
      {broad&&<div className="mt-4 rounded-xl border-2 border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><div className="font-bold">Broad Delegation</div><p>This authority applies across all approved records within the selected scope for the effective period.</p><label className="mt-2 flex items-center gap-2 font-semibold"><input type="checkbox" checked={form.broad_scope_confirmed} onChange={e=>setForm({...form,broad_scope_confirmed:e.target.checked})}/> I confirm this broad delegation is necessary and appropriately justified.</label></div>}
      <div className="mt-4 flex justify-end"><button className="btn-primary" disabled={!complete} onClick={()=>setConfirming(true)}>Review Delegation</button></div>
    </section>
    <section className="card"><div className="flex flex-wrap gap-2 border-b p-4"><input className="input max-w-sm" placeholder="Search employee, ID, delegation or authority..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="input max-w-40" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}>{["All","Scheduled","Active","Expired","Revoked"].map(x=><option key={x}>{x}</option>)}</select><select className="input max-w-40" value={departmentFilter} onChange={e=>setDepartmentFilter(e.target.value)}>{["All","Procurement","Warehouse"].map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto"><table className="table-base min-w-[82rem]"><thead><tr>{["Delegation ID","Delegate","Department / Normal Role","Delegated Authority","Scope","Effective Period","Created By","Status","Action"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="font-semibold">{r.delegation_number}</td><td>{r.employee_code} — {r.delegate_name}</td><td>{r.department}<div className="text-slate-500">{r.normal_role_label}</div></td><td>{r.authority_label}</td><td>{SCOPE_LABELS[r.scope_type]||r.scope_type}{r.scope_id?` · ${r.scope_id}`:""}</td><td>{displayDate(r.effective_from)}<br/>{displayDate(r.effective_until)}</td><td>{r.created_by_name}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.effective_status==="Active"?"bg-emerald-100 text-emerald-800":r.effective_status==="Revoked"?"bg-rose-100 text-rose-800":"bg-slate-100 text-slate-700"}`}>{r.effective_status}</span></td><td>{["Active","Scheduled"].includes(r.effective_status)?<button className="rounded-lg border border-rose-300 px-3 py-2 font-semibold text-rose-700 hover:bg-rose-50" onClick={()=>setRevoking(r)}>Revoke</button>:"—"}</td></tr>)}</tbody></table></div></section>
    {confirming&&<Modal title="Confirm Controlled Delegation" onClose={()=>setConfirming(false)}><dl className="record-detail-grid"><div><dt>Delegate</dt><dd>{employee?.name}</dd></div><div><dt>Department</dt><dd>{employee?.department}</dd></div><div><dt>Normal Role</dt><dd>{employee?.role_label}</dd></div><div><dt>Temporary Authority</dt><dd>{authority?.label}</dd></div><div><dt>Scope</dt><dd>{selectedScope}</dd></div><div><dt>Effective Period</dt><dd>{displayDate(form.effective_from)} — {displayDate(form.effective_until)}</dd></div><div><dt>Reason</dt><dd>{catalog.reasons.find(r=>r.code===form.reason_code)?.label}</dd></div></dl><div className="mt-4 rounded-lg bg-indigo-50 p-3 text-sm font-semibold text-indigo-900">This delegation is temporary and does not change the employee&apos;s normal role.</div><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setConfirming(false)}>Cancel</button><button className="btn-primary" onClick={create}>Confirm Delegation</button></div></Modal>}
    {revoking&&<Modal title="Revoke Delegation" onClose={()=>setRevoking(null)}><p className="text-sm text-slate-600">Revoking {revoking.delegation_number} stops the temporary permission immediately. The permanent history will remain.</p><label className="mt-4 block text-sm font-medium">Revocation Reason<textarea className="input mt-1 min-h-24" value={revocationReason} onChange={e=>setRevocationReason(e.target.value)}/></label><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setRevoking(null)}>Cancel</button><button className="rounded-lg bg-rose-700 px-4 py-2 font-semibold text-white disabled:opacity-50" disabled={revocationReason.trim().length<5} onClick={revoke}>Confirm Revocation</button></div></Modal>}
    {audit&&<Modal title="Delegated Authority Audit History" wide onClose={()=>setAudit(null)}><h3 className="font-semibold text-indigo-950">Lifecycle History</h3><div className="mt-2 overflow-x-auto"><table className="table-base"><thead><tr><th>Delegation</th><th>Event</th><th>Changed By</th><th>Date/Time</th><th>Reason</th></tr></thead><tbody>{audit.history.map(row=><tr key={row.id}><td>{row.delegation_number}</td><td>{row.event_type}</td><td>{row.changed_by_name}</td><td>{displayDate(row.changed_at)}</td><td>{row.reason||"—"}</td></tr>)}</tbody></table></div><h3 className="mt-6 font-semibold text-indigo-950">Delegated Authority Usage</h3><div className="mt-2 overflow-x-auto"><table className="table-base"><thead><tr><th>Delegation</th><th>Authority</th><th>Performed By</th><th>Transaction</th><th>Action</th><th>Date/Time</th></tr></thead><tbody>{audit.uses.map(row=><tr key={row.id}><td>{row.delegation_number}</td><td>{row.authority_code}</td><td>{row.performed_by_name}</td><td>{row.table_name} #{row.record_id}</td><td>{row.action}</td><td>{displayDate(row.used_at)}</td></tr>)}</tbody></table></div></Modal>}
  </div>;
}
