import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import client from '../api/client';
import { useAuth } from '../contexts/AuthContext';
import { ProductBrand } from '../components/Branding';

const registrationInitial={company_name:'',company_key:'',company_email:'',admin_name:'',admin_email:'',username:'',password:'',confirm_password:''};

export default function Login(){
  const {login}=useAuth();const navigate=useNavigate();
  const [mode,setMode]=useState('login');const [companyKey,setCompanyKey]=useState(localStorage.getItem('procuraflow_company_key')||'default');const [username,setUsername]=useState('');const [password,setPassword]=useState('');
  const [registration,setRegistration]=useState(registrationInitial);const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
  async function handleLogin(event){event.preventDefault();setError('');setLoading(true);try{await login(companyKey,username,password);navigate('/');}catch(err){setError(err?.response?.data?.error||'Login failed');}finally{setLoading(false);}}
  async function handleRegistration(event){event.preventDefault();setError('');setMessage('');if(registration.password!==registration.confirm_password){setError('Passwords do not match');return;}setLoading(true);try{const payload={...registration};delete payload.confirm_password;const {data}=await client.post('/auth/register-company',payload,{headers:{'X-Company-Key':''}});setCompanyKey(data.company_key);setUsername(registration.username);setPassword('');setRegistration(registrationInitial);setMode('login');setMessage(`${data.company_name} was registered. Sign in with company ID “${data.company_key}”.`);}catch(err){setError(err?.response?.data?.error||'Company registration failed');}finally{setLoading(false);}}
  const update=(key,value)=>setRegistration(current=>({...current,[key]:value, ...(key==='company_name'&&!current.company_key?{company_key:value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}:{})}));
  return <div className="min-h-screen bg-slate-950 px-4 py-10"><div className="mx-auto w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="p-7 sm:p-9"><div className="flex justify-center"><ProductBrand/></div><div className="my-5 border-t border-slate-200"/>
    <div className="mb-5 grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button type="button" className={mode==='login'?'btn-primary':'btn-secondary'} onClick={()=>{setMode('login');setError('');}}>Company Sign In</button><button type="button" className={mode==='register'?'btn-primary':'btn-secondary'} onClick={()=>{setMode('register');setError('');}}>Register New Company</button></div>
    {message&&<div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}{error&&<div className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    {mode==='login'?<form onSubmit={handleLogin} className="space-y-4"><div><label className="text-sm font-medium text-slate-700">Company Login ID</label><input className="input mt-1" value={companyKey} onChange={e=>setCompanyKey(e.target.value.toLowerCase())} placeholder="your-company" autoFocus/><p className="mt-1 text-xs text-slate-500">Existing installations use <strong>default</strong>.</p></div><div><label className="text-sm font-medium text-slate-700">Username</label><input className="input mt-1" value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></div><div><label className="text-sm font-medium text-slate-700">Password</label><input className="input mt-1" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div><button className="btn-primary w-full" disabled={loading}>{loading?'Signing in...':'Sign In'}</button></form>
    :<form onSubmit={handleRegistration} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><h1 className="text-lg font-semibold text-slate-900">Create a protected company workspace</h1><p className="mt-1 text-sm text-slate-500">Your company receives an isolated database and its own login ID. The first account is the Supply Chain Manager.</p></div><div><label className="text-sm font-medium">Company Name</label><input className="input mt-1" value={registration.company_name} onChange={e=>update('company_name',e.target.value)} required/></div><div><label className="text-sm font-medium">Company Login ID</label><input className="input mt-1" value={registration.company_key} onChange={e=>update('company_key',e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} pattern="[a-z0-9][a-z0-9-]{2,47}" required/></div><div><label className="text-sm font-medium">Company Email</label><input className="input mt-1" type="email" value={registration.company_email} onChange={e=>update('company_email',e.target.value)}/></div><div><label className="text-sm font-medium">Administrator Name</label><input className="input mt-1" value={registration.admin_name} onChange={e=>update('admin_name',e.target.value)} required/></div><div><label className="text-sm font-medium">Administrator Email</label><input className="input mt-1" type="email" value={registration.admin_email} onChange={e=>update('admin_email',e.target.value)}/></div><div><label className="text-sm font-medium">Administrator Username</label><input className="input mt-1" value={registration.username} onChange={e=>update('username',e.target.value)} required/></div><div><label className="text-sm font-medium">Password</label><input className="input mt-1" type="password" minLength="10" value={registration.password} onChange={e=>update('password',e.target.value)} required/></div><div><label className="text-sm font-medium">Confirm Password</label><input className="input mt-1" type="password" minLength="10" value={registration.confirm_password} onChange={e=>update('confirm_password',e.target.value)} required/></div><div className="sm:col-span-2"><button className="btn-primary w-full" disabled={loading}>{loading?'Creating isolated workspace...':'Register Company & Administrator'}</button></div></form>}
  </div></div></div>;
}
