import React, { useEffect, useMemo, useState } from 'react';
import client from '../api/client';

type Status = 'Online'|'Away'|'Offline';
type ActivityUser = { id:number; full_name:string; username:string; role:string; is_active:number; locked_reason?:string|null; employee_code?:string|null; department_name?:string|null; warehouse_name?:string|null; last_seen?:string|null; page_path?:string|null; current_action?:string|null; activity_status:Status; seconds_since_activity?:number|null };

const statusStyle:Record<Status,{dot:string,badge:string,bar:string}>={
  Online:{dot:'bg-emerald-400',badge:'bg-emerald-50 text-emerald-700 ring-emerald-600/20',bar:'bg-emerald-500'},
  Away:{dot:'bg-amber-400',badge:'bg-amber-50 text-amber-700 ring-amber-600/20',bar:'bg-amber-400'},
  Offline:{dot:'bg-slate-400',badge:'bg-slate-100 text-slate-600 ring-slate-500/20',bar:'bg-slate-400'},
};
const roleLabel=(role:string)=>role.replace(/([a-z])([A-Z])/g,'$1 $2');
function relativeTime(seconds?:number|null){if(seconds==null)return'No activity recorded';if(seconds<20)return'Just now';if(seconds<60)return`${seconds} sec ago`;if(seconds<3600)return`${Math.floor(seconds/60)} min ago`;if(seconds<86400)return`${Math.floor(seconds/3600)} hr ago`;return`${Math.floor(seconds/86400)} days ago`;}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();}

export default function LiveUserActivityPage(){
  const [users,setUsers]=useState<ActivityUser[]>([]);const [generatedAt,setGeneratedAt]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filter,setFilter]=useState<'All'|Status>('All');const [search,setSearch]=useState('');const [selectedId,setSelectedId]=useState<number|null>(null);
  async function load(){try{const{data}=await client.get('/dashboard/activity/live');setUsers(data.users||[]);setGeneratedAt(data.generated_at);setError('');}catch(e:any){setError(e?.response?.data?.error||'Unable to load live user activity.');}finally{setLoading(false);}}
  useEffect(()=>{load();const timer=window.setInterval(load,10_000);return()=>window.clearInterval(timer);},[]);
  const counts=useMemo(()=>({Online:users.filter(u=>u.activity_status==='Online').length,Away:users.filter(u=>u.activity_status==='Away').length,Offline:users.filter(u=>u.activity_status==='Offline').length}),[users]);
  const presence=users.length?Math.round((counts.Online/users.length)*100):0;
  const shown=useMemo(()=>users.filter(u=>(filter==='All'||u.activity_status===filter)&&(!search||`${u.full_name} ${u.username} ${u.role} ${u.department_name||''} ${u.current_action||''}`.toLowerCase().includes(search.toLowerCase()))),[users,filter,search]);
  const selected=users.find(user=>user.id===selectedId)||null;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-blue-900 px-6 py-7 text-white shadow-2xl shadow-indigo-950/20 lg:px-8">
      <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-2xl"/><div className="absolute bottom-0 left-1/3 h-32 w-80 bg-indigo-400/10 blur-3xl"/>
      <div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-cyan-400/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.22em] text-cyan-300 ring-1 ring-cyan-300/20"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Live Operations Intelligence</div><h1 className="text-3xl font-bold tracking-tight lg:text-4xl">Workforce Activity Command Center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Executive visibility into authenticated users, operational presence, and the ProcuraFlow workspaces currently in use.</p></div>
        <div className="grid min-w-[300px] grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[0.07] p-4 ring-1 ring-white/10 backdrop-blur"><div className="text-[10px] uppercase tracking-widest text-slate-400">Workforce presence</div><div className="mt-1 text-3xl font-bold">{presence}<span className="text-base text-cyan-300">%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-emerald-400 transition-all duration-700" style={{width:`${presence}%`}}/></div></div><div className="rounded-2xl bg-white/[0.07] p-4 ring-1 ring-white/10 backdrop-blur"><div className="text-[10px] uppercase tracking-widest text-slate-400">Live synchronization</div><div className="mt-2 flex items-center gap-2 text-sm font-semibold"><span className="relative flex h-3 w-3"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-60"/><span className="relative h-3 w-3 rounded-full bg-emerald-400"/></span>Connected</div><div className="mt-2 text-xs text-slate-400">Updated {generatedAt?new Date(generatedAt).toLocaleTimeString():'—'}</div></div></div>
      </div>
    </section>

    <section className="grid gap-4 md:grid-cols-4">
      <button onClick={()=>setFilter('All')} className={`group card relative overflow-hidden border p-5 text-left transition-all hover:-translate-y-1 hover:shadow-lg ${filter==='All'?'border-indigo-400 ring-2 ring-indigo-100':'border-slate-200'}`}><div className="absolute -right-5 -top-5 h-20 w-20 rounded-full bg-indigo-500/10"/><div className="relative text-xs font-bold uppercase tracking-wider text-slate-500">Total Accounts</div><div className="relative mt-2 text-3xl font-bold text-slate-900">{users.length}</div><div className="relative mt-2 text-xs text-indigo-600">Authenticated workforce directory</div></button>
      {(['Online','Away','Offline'] as Status[]).map(status=><button key={status} onClick={()=>setFilter(filter===status?'All':status)} className={`group card border p-5 text-left transition-all hover:-translate-y-1 hover:shadow-lg ${filter===status?'border-indigo-400 ring-2 ring-indigo-100':'border-slate-200'}`}><div className="flex items-start justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-slate-500">{status} Now</div><div className="mt-2 text-3xl font-bold text-slate-900">{counts[status]}</div></div><span className={`mt-1 h-3.5 w-3.5 rounded-full ${statusStyle[status].dot} ${status==='Online'?'animate-pulse shadow-lg shadow-emerald-300':''}`}/></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${statusStyle[status].bar}`} style={{width:`${users.length?counts[status]/users.length*100:0}%`}}/></div></button>)}
    </section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
      <div className="card overflow-hidden border border-slate-200 shadow-sm"><div className="border-b border-slate-100 bg-gradient-to-r from-slate-50 to-indigo-50/50 px-5 py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold text-slate-900">Live Activity Directory</h2><p className="text-xs text-slate-500">Select a user to open an executive activity profile.</p></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><span className="pointer-events-none absolute left-3 top-2.5 text-slate-400">⌕</span><input className="input min-w-64 pl-8" placeholder="Search user, role, activity…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input sm:w-36" value={filter} onChange={e=>setFilter(e.target.value as any)}><option>All</option><option>Online</option><option>Away</option><option>Offline</option></select></div></div></div>
        {error?<div className="p-6 text-sm text-red-700">{error}</div>:loading?<div className="p-14 text-center text-slate-400">Connecting to live activity…</div>:<div className="overflow-x-auto"><table className="table"><thead><tr><th>User Identity</th><th>Business Assignment</th><th>Presence</th><th>Current Workspace</th><th>Last Signal</th></tr></thead><tbody>{shown.map(user=>{const style=statusStyle[user.activity_status];return <tr key={user.id} onClick={()=>setSelectedId(user.id)} className={`cursor-pointer transition-colors hover:bg-indigo-50/60 ${selectedId===user.id?'bg-indigo-50 ring-1 ring-inset ring-indigo-100':''}`}><td><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-600 to-blue-500 text-xs font-bold text-white shadow-sm">{initials(user.full_name)}</div><div><div className="font-semibold text-slate-800">{user.full_name}</div><div className="font-mono text-xs text-indigo-600">{user.username}</div></div></div></td><td><div className="text-sm font-medium text-slate-700">{roleLabel(user.role)}</div><div className="text-xs text-slate-400">{user.department_name||'Unassigned department'}</div></td><td><span className={`inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${style.badge}`}><span className={`h-2 w-2 rounded-full ${style.dot} ${user.activity_status==='Online'?'animate-pulse':''}`}/>{user.activity_status}</span></td><td><div className="max-w-xs truncate text-sm font-medium text-slate-700">{user.current_action||'No current activity'}</div><div className="text-xs text-slate-400">{user.page_path||'—'}</div></td><td><div className="text-sm text-slate-700">{relativeTime(user.seconds_since_activity)}</div><div className="text-xs text-slate-400">{user.last_seen?new Date(`${user.last_seen}Z`).toLocaleTimeString():'Never'}</div></td></tr>})}{shown.length===0&&<tr><td colSpan={5} className="py-14 text-center text-slate-400">No users match the selected criteria.</td></tr>}</tbody></table></div>}
        <div className="flex items-center justify-between border-t border-slate-100 bg-slate-50 px-5 py-3 text-xs text-slate-500"><span>Showing {shown.length} of {users.length} accounts</span><span>Automatic refresh · 10 sec</span></div>
      </div>

      <aside className="card h-fit overflow-hidden border border-slate-200 shadow-sm xl:sticky xl:top-5">{selected?<><div className="bg-gradient-to-br from-indigo-950 to-blue-800 p-5 text-white"><button className="float-right text-indigo-200 hover:text-white" onClick={()=>setSelectedId(null)}>×</button><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10 text-lg font-bold ring-1 ring-white/20">{initials(selected.full_name)}</div><h3 className="mt-3 text-lg font-bold">{selected.full_name}</h3><div className="font-mono text-xs text-cyan-300">{selected.username}</div></div><div className="space-y-4 p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Current status</span><span className={`inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${statusStyle[selected.activity_status].badge}`}><span className={`h-2 w-2 rounded-full ${statusStyle[selected.activity_status].dot}`}/>{selected.activity_status}</span></div><div className="rounded-xl bg-indigo-50 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-indigo-500">Current activity</div><div className="mt-1 text-sm font-semibold text-indigo-950">{selected.current_action||'No current activity'}</div><div className="mt-1 text-xs text-indigo-500">{selected.page_path||'No workspace recorded'}</div></div>{[['Role',roleLabel(selected.role)],['Employee ID',selected.employee_code||'Not linked'],['Department',selected.department_name||'Not assigned'],['Warehouse',selected.warehouse_name||'Not assigned'],['Last activity',relativeTime(selected.seconds_since_activity)]].map(([label,value])=><div key={label} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><span className="text-right font-medium text-slate-800">{value}</span></div>)}{selected.locked_reason&&<div className="rounded-lg bg-red-50 p-3 text-xs text-red-700">Account locked: {selected.locked_reason}</div>}</div></>:<div className="flex min-h-80 flex-col items-center justify-center p-8 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-50 text-2xl text-indigo-500">◎</div><h3 className="mt-4 font-semibold text-slate-800">Activity Profile</h3><p className="mt-1 text-sm leading-5 text-slate-500">Select any user from the live directory to inspect their operational presence and current workspace.</p></div>}</aside>
    </section>
    <div className="flex items-start gap-2 rounded-xl border border-blue-100 bg-blue-50/60 px-4 py-3 text-xs text-blue-700"><span>ⓘ</span><span><strong>Privacy by design:</strong> monitoring records module and page activity only. Passwords, field values, document contents, and typed form data are never captured.</span></div>
  </div>;
}
