import React from 'react';
import { Link } from 'react-router-dom';

type StartCard={title:string;audience:string;steps:string[];tip?:string};

const procurement:StartCard[]=[
  {title:'1. Review demand and create a PR',audience:'Purchase Officer, Purchase Manager, Supply Chain Manager and authorized Warehouse staff',steps:['Open Purchase Requisitions and create a draft with the required date, purpose and one or more item lines.','Review ProcuraFlow-generated low-stock PRs alongside manually created requests.','Submit the PR and use its unique reference number for all follow-up.'],tip:'An approved PR remains Submitted until its quantity is placed on a PO. A partially ordered PR remains open for its balance.'},
  {title:'2. Source and compare quotations',audience:'Procurement',steps:['Create an RFQ from the approved requirement and record invited suppliers.','Capture price, freight, tax, currency, lead time, payment terms, warranty, quality and supplier score.','Compare total landed cost and supporting evidence; do not select a supplier on lowest unit price alone.']},
  {title:'3. Create and approve the PO',audience:'Procurement and authorized approvers',steps:['Select one or more Submitted PRs; lines fill immediately and matching items are consolidated.','Select the supplier and verify outstanding PR quantities, UOM, prior supplier price/tax, market comparison and committed delivery date.','Submit the PO. Open approval work from My Task List and review the complete document before deciding.','For a PO above the Supply Chain Manager limit, print the uniquely referenced Management Approval Request, obtain external approval and upload the evidence.','Print or download the approved company-record PO. It is locked from amendment and remains receivable until all ordered quantities are accepted.'],tip:'Creators normally cannot approve their own work. The Supply Chain Manager exception applies to permitted transactions within authority, never to an over-limit PO without external evidence.'},
  {title:'4. Verify invoice evidence',audience:'Procurement; Supply Chain Manager confirms',steps:['Record the unique supplier invoice against its PO and GRN.','Review PO value, accepted receipt value, invoice value, tax and every variance.','Use Finance Payment Verification as read-only payment evidence for Finance.']},
];

const warehouse:StartCard[]=[
  {title:'1. Plan and receive an approved PO',audience:'Assigned Warehouse team',steps:['Use Goods Receipt to view only approved, printed and still-open POs.','Select the PO; outstanding items, supplier and committed date fill automatically.','Confirm delivery details, assigned warehouse and destination Zone/Rack/Shelf/Bin.','Enter received, accepted and rejected quantities, plus batch, expiry and rejection reason where applicable.','Post and download the professional GRN. Accepted quantity updates FIFO stock; partial receipt keeps the PO open.'],tip:'The warehouse is derived from the employee assignment and cannot be changed to another employee’s warehouse.'},
  {title:'2. Issue and return materials',audience:'Storekeeper, Warehouse Supervisor and Warehouse Manager',steps:['Create a Material Issue, select the recipient and add one or more items.','Review displayed location, available stock and issue UOM before entering quantity.','Submit for approval when the configured threshold or item control requires it; otherwise post through the permitted workflow.','For a return, select the original responsibility, outstanding quantity and return condition.'],tip:'Zero, unavailable or excessive quantities are blocked. FIFO layers used by a posted issue remain in the permanent ledger.'},
  {title:'3. Transfer, relocate and adjust stock',audience:'Authorized Warehouse roles',steps:['Use Warehouse Transfer for movement between assigned warehouses and capture transport mode, tracking, vehicle, driver and remarks.','Use BIN Transfer to relocate stock between controlled locations inside the permitted warehouse.','Use Stock Adjustment only with a clear reason and manager approval.','Never edit or delete a posted movement; create a controlled corrective transaction.']},
  {title:'4. Control stock and tools',audience:'Warehouse and Inventory roles',steps:['Review Real-Time Stock, FIFO Valuation, expiry, ABC and dead-stock screens.','Perform cycle counts, submit variances and route approval to someone other than the counter.','Track tools by unique ID, serial number, make, model, issue date and return condition.','Investigate low stock, expiry, overdue returnables and damaged/lost/repair-required tools from tasks and reports.']},
];

function Section({title,subtitle,cards,color}:{title:string;subtitle:string;cards:StartCard[];color:string}){return <section className="card overflow-hidden"><div className={`bg-gradient-to-r ${color} p-5 text-white`}><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-white/80">{subtitle}</p></div><div className="grid gap-4 p-5 xl:grid-cols-2">{cards.map(card=><article key={card.title} className="rounded-xl border border-slate-200 bg-slate-50/70 p-4"><h3 className="font-semibold text-slate-900">{card.title}</h3><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-indigo-600">{card.audience}</p><ol className="mt-3 space-y-2 text-sm text-slate-600">{card.steps.map((step,index)=><li key={step} className="flex gap-2"><span className="font-semibold text-slate-400">{index+1}.</span><span>{step}</span></li>)}</ol>{card.tip&&<div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900"><strong>Control:</strong> {card.tip}</div>}</article>)}</div></section>}

export default function QuickStartPage(){return <div className="space-y-5"><header className="rounded-2xl bg-gradient-to-br from-slate-950 via-indigo-950 to-cyan-800 p-6 text-white shadow-xl"><div className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-200">ProcuraFlow Operations</div><h1 className="mt-2 text-3xl font-bold">Procurement & Warehouse Quick Start</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-200">A practical route from an approved business need to supplier commitment, controlled receiving, accountable inventory movement and management reporting.</p><div className="mt-5 flex flex-wrap gap-2"><Link className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-indigo-800" to="/help?department=Procurement">Full Procurement Guide</Link><Link className="rounded-lg border border-white/30 px-4 py-2 text-sm font-semibold text-white" to="/help?department=Warehouse">Full Warehouse Guide</Link><Link className="rounded-lg border border-white/30 px-4 py-2 text-sm font-semibold text-white" to="/reports">Open Reports</Link></div></header>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Start every day','Open the dashboard task summary; select a group to expand the full task list.'],['Open the source','Double-click a task to review its original PR, PO, GRN or approval screen.'],['Protect the audit trail','Save drafts, confirm before posting and never alter a posted transaction.'],['Use assigned scope','Warehouse work is restricted to the employee’s authorized warehouse and locations.']].map(([title,text])=><div key={title} className="card p-4"><div className="font-semibold text-slate-900">{title}</div><p className="mt-1 text-sm text-slate-600">{text}</p></div>)}</div>
  <Section title="Procurement: Requisition to Payment Evidence" subtitle="Demand, sourcing, delegated approval, purchase commitment and three-way verification." cards={procurement} color="from-indigo-700 to-blue-600"/>
  <Section title="Warehouse: Receipt to Stock Accountability" subtitle="Assigned-warehouse receiving, FIFO movement, location control and permanent inventory history." cards={warehouse} color="from-emerald-700 to-cyan-600"/>
  <section className="card p-5"><h2 className="text-lg font-semibold text-slate-900">Reports and controlled documents</h2><div className="mt-3 grid gap-4 md:grid-cols-3"><div><h3 className="font-semibold text-indigo-700">Procurement</h3><p className="mt-1 text-sm text-slate-600">PR, RFQ, quotation comparison, PO, delivery, aging, supplier purchase, price variance and finance verification reports.</p></div><div><h3 className="font-semibold text-emerald-700">Warehouse & Inventory</h3><p className="mt-1 text-sm text-slate-600">GRN, receiving, issues, returns, transfers, adjustments, stock ledger, balance, FIFO, batch, low-stock and cycle-count reports.</p></div><div><h3 className="font-semibold text-cyan-700">Output standard</h3><p className="mt-1 text-sm text-slate-600">Apply available filters, verify company currency and totals, then download Excel/PDF or print. Controlled documents include branding, signatures/times, repeating table headers, page breaks and page numbers.</p></div></div></section>
</div>}
