import React,{useEffect,useState}from'react';
import client from'../api/client';

const tabs=['Countries','Cities','Currencies','Exchange Rates','Holidays','Shifts','Availability','Coverage','Helper Supervision'];
export default function WorkforceSetupPage(){
 const[data,setData]=useState<any>({countries:[],currencies:[],exchange_rates:[],holidays:[],shifts:[],availability:[],coverage:[],employees:[],departments:[]});
 const[tab,setTab]=useState('Countries'),[form,setForm]=useState<any>({}),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=()=>Promise.all([client.get('/workforce/reference'),client.get('/workforce/availability'),client.get('/workforce/coverage'),client.get('/masters/employee-directory'),client.get('/masters/departments')]).then(([r,a,c,e,d])=>setData({...r.data,availability:a.data,coverage:c.data,employees:e.data,departments:d.data}));
 useEffect(()=>{load().catch(e=>setError(e.response?.data?.error||'Unable to load setup data'));},[]);
 async function save(){try{if(tab==='Shifts')await client.put(`/workforce/shifts/${form.id}`,form);else if(tab==='Helper Supervision')await client.put('/workforce/helper-supervisor-roles',{roles:form.roles||data.helper_supervisor_roles});else{const endpoint:any={Countries:'countries',Cities:'cities',Currencies:'currencies','Exchange Rates':'exchange-rates',Holidays:'holidays',Availability:'availability',Coverage:'coverage'};await client.post(`/workforce/${endpoint[tab]}`,form);}setForm({});setMessage(`${tab} saved successfully.`);setError('');await load();}catch(e:any){setError(e.response?.data?.error||'Unable to save record');}}
 async function synchronizeHolidays(){try{const country=form.country_code||data.company?.country_code,year=Number(form.year||new Date().getFullYear());const res=await client.post('/workforce/holidays/synchronize',{country_code:country,year});setMessage(`${res.data.rows.length} holidays loaded; ${res.data.added} new records stored.`);setForm({...form,country_code:country,year});await load();}catch(e:any){setError(e.response?.data?.error||'Holiday synchronization failed');}}
 const rows=tab==='Countries'?data.countries:tab==='Cities'?data.cities:tab==='Currencies'?data.currencies:tab==='Exchange Rates'?data.exchange_rates:tab==='Holidays'?data.holidays:tab==='Availability'?data.availability:tab==='Coverage'?data.coverage:tab==='Helper Supervision'?[]:data.shifts;
 const input=(key:string,label:string,type='text')=><label className="text-sm font-medium text-slate-700">{label}<input type={type} className="input mt-1" value={form[key]??''} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 return <div><h1 className="text-2xl font-bold">Country, Currency, Holiday & Workforce Setup</h1><p className="mb-4 text-sm text-slate-500">Supply Chain Manager controls for enterprise masters, employee availability, minimum coverage and shift rules.</p><div className="mb-4 flex flex-wrap gap-2">{tabs.map(x=><button className={tab===x?'btn-primary':'btn-secondary'} onClick={()=>{setTab(x);setForm({});setMessage('');setError('');}} key={x}>{x}</button>)}</div>
 <div className="card mb-4 grid gap-3 p-4 md:grid-cols-4">
 {tab==='Countries'&&<>{input('country_name','Country Name')}{input('iso_alpha2','ISO Alpha-2')}{input('iso_alpha3','ISO Alpha-3')}<label className="text-sm font-medium">Default Currency<select className="input mt-1" value={form.default_currency_code||''} onChange={e=>setForm({...form,default_currency_code:e.target.value})}><option value="">Select</option>{data.currencies.map((c:any)=><option key={c.id}>{c.currency_code}</option>)}</select></label></>}
 {tab==='Cities'&&<><label className="text-sm font-medium">Country<select className="input mt-1" value={form.country_code||''} onChange={e=>setForm({...form,country_code:e.target.value})}><option value="">Select</option>{data.countries.map((c:any)=><option key={c.id} value={c.country_code}>{c.country_name}</option>)}</select></label>{input('city_name','City Name')}{input('city_code','City Code')}{input('state_province_region','State / Province / Region')}</>}
 {tab==='Currencies'&&<>{input('currency_code','Currency Code')}{input('currency_name','Currency Name')}{input('currency_symbol','Symbol')}{input('decimal_places','Decimal Places','number')}</>}
 {tab==='Exchange Rates'&&<><label className="text-sm font-medium">From Currency<select className="input mt-1" value={form.from_currency||''} onChange={e=>setForm({...form,from_currency:e.target.value})}><option value="">Select</option>{data.currencies.map((c:any)=><option key={c.id}>{c.currency_code}</option>)}</select></label><label className="text-sm font-medium">To Currency<select className="input mt-1" value={form.to_currency||''} onChange={e=>setForm({...form,to_currency:e.target.value})}><option value="">Select</option>{data.currencies.map((c:any)=><option key={c.id}>{c.currency_code}</option>)}</select></label>{input('rate','Conversion Rate','number')}{input('effective_date','Effective Date','date')}</>}
 {tab==='Holidays'&&<><label className="text-sm font-medium">Country<select className="input mt-1" value={form.country_code||data.company?.country_code||''} onChange={e=>setForm({...form,country_code:e.target.value})}><option value="">Select</option>{data.countries.map((c:any)=><option value={c.country_code} key={c.id}>{c.country_name}</option>)}</select></label>{input('year','Calendar Year','number')}<button className="btn-secondary self-end" onClick={synchronizeHolidays}>Synchronize Official Holidays</button>{input('holiday_name','Manual Holiday Name')}{input('holiday_date','Holiday Date','date')}{input('source','Official Source')}</>}
 {tab==='Shifts'&&<><label className="text-sm font-medium">Shift<select className="input mt-1" value={form.id||''} onChange={e=>setForm(data.shifts.find((s:any)=>s.id===Number(e.target.value))||{})}><option value="">Select shift</option>{data.shifts.map((s:any)=><option key={s.id} value={s.id}>{s.shift_label}</option>)}</select></label>{input('shift_label','Shift Label')}{input('start_time','Start Time','time')}{input('end_time','End Time','time')}{input('break_minutes','Break Minutes','number')}{input('effective_from','Effective From','date')}</>}
 {tab==='Availability'&&<><label className="text-sm font-medium">Employee<select className="input mt-1" value={form.employee_id||''} onChange={e=>setForm({...form,employee_id:Number(e.target.value)})}><option value="">Select employee</option>{data.employees.map((e:any)=><option key={e.id} value={e.id}>{e.employee_code} — {e.name}</option>)}</select></label>{input('date_from','From Date','date')}{input('date_to','To Date','date')}<label className="text-sm font-medium">Availability Status<select className="input mt-1" value={form.availability_status||''} onChange={e=>setForm({...form,availability_status:e.target.value})}><option value="">Select</option>{['Available','Leave','Training','Sick','Unavailable'].map(x=><option key={x}>{x}</option>)}</select></label>{input('reason','Reason')}</>}
 {tab==='Coverage'&&<><label className="text-sm font-medium">Department<select className="input mt-1" value={form.department_id||''} onChange={e=>setForm({...form,department_id:Number(e.target.value)})}><option value="">Select</option>{data.departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{input('role_code','Role Code')}<label className="text-sm font-medium">Shift<select className="input mt-1" value={form.shift_id||''} onChange={e=>setForm({...form,shift_id:Number(e.target.value)})}><option value="">Select</option>{data.shifts.map((s:any)=><option key={s.id} value={s.id}>{s.shift_label}</option>)}</select></label>{input('minimum_staff','Minimum Staff','number')}</>}
 {tab==='Helper Supervision'&&<div className="md:col-span-4"><div className="mb-2 text-sm font-semibold">Roles permitted to supervise Helpers</div><div className="flex flex-wrap gap-4">{['WarehouseManager','WarehouseSupervisor','Storekeeper'].map(role=>{const selected=form.roles||data.helper_supervisor_roles||[];return <label key={role} className="flex items-center gap-2 rounded-lg border p-3"><input type="checkbox" checked={selected.includes(role)} onChange={e=>setForm({...form,roles:e.target.checked?[...selected,role]:selected.filter((x:string)=>x!==role)})}/>{role.replace(/([a-z])([A-Z])/g,'$1 $2')}</label>})}</div></div>}
 <button className="btn-primary md:col-span-4" disabled={tab==='Shifts'&&!form.id} onClick={save}>{tab==='Shifts'?'Update Shift':`Save ${tab}`}</button></div>
 {message&&<div className="mb-3 rounded bg-emerald-50 p-3 text-emerald-700">{message}</div>}{error&&<div className="mb-3 rounded bg-rose-50 p-3 text-rose-700">{error}</div>}<div className="card overflow-x-auto"><table className="table-base"><thead><tr>{rows[0]&&Object.keys(rows[0]).slice(0,9).map(k=><th key={k}>{k.replace(/_/g,' ')}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}>{Object.keys(r).slice(0,9).map(k=><td key={k}>{String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div></div>;
}
