import React,{useEffect,useMemo,useState}from'react';
import client from'../api/client';
import{useAuth}from'../contexts/AuthContext';
import{useBranding}from'../contexts/BrandingContext';
import StatusBadge from'../components/StatusBadge';
import{downloadElementPdf}from'../utils/downloadPdf';
import{CompanyLogo}from'../components/Branding';

const shiftTone:Record<string,string>={MORNING:'bg-amber-50 text-amber-800 border-amber-200',AFTERNOON:'bg-sky-50 text-sky-800 border-sky-200',EVENING:'bg-violet-50 text-violet-800 border-violet-200',OFF:'bg-slate-100 text-slate-700 border-slate-200',HOLIDAY:'bg-rose-50 text-rose-800 border-rose-200'};
export default function WorkCalendarPage({scope,admin=false}:{scope?:'Warehouse'|'Procurement';admin?:boolean}){
 const{user}=useAuth(),{company}=useBranding();const[period,setPeriod]=useState('current'),[view,setView]=useState<'calendar'|'roster'>('calendar'),[adminScope,setAdminScope]=useState<'Warehouse'|'Procurement'>('Warehouse'),[warehouseId,setWarehouseId]=useState(''),[data,setData]=useState<any>({rows:[],warehouses:[]}),[refs,setRefs]=useState<any>({shifts:[]}),[error,setError]=useState(''),[editing,setEditing]=useState<any>(),[selectedDate,setSelectedDate]=useState('');const effectiveScope=scope||adminScope;const effectiveWarehouseId=effectiveScope==='Warehouse'?warehouseId:'';
 const load=()=>Promise.all([client.get('/workforce/calendar',{params:{scope:effectiveScope,period,...(effectiveWarehouseId?{warehouse_id:effectiveWarehouseId}:{})}}),client.get('/workforce/reference')]).then(([c,r])=>{setData(c.data);setRefs(r.data);setError('');}).catch(e=>setError(e.response?.data?.error||'Unable to load workday calendar'));
 useEffect(()=>{if(effectiveScope==='Procurement'&&warehouseId)setWarehouseId('');setSelectedDate('');load();},[period,effectiveScope,effectiveWarehouseId]);
 const days=useMemo<Array<{date:string;rows:any[]}>>(()=>{if(!data.range?.from||!data.range?.to)return[];const grouped=data.rows.reduce((a:any,r:any)=>{(a[r.calendar_date]??=[]).push(r);return a;},{}),out:Array<{date:string;rows:any[]}>=[];for(let cursor=new Date(`${data.range.from}T00:00:00Z`),end=new Date(`${data.range.to}T00:00:00Z`);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+1)){const date=cursor.toISOString().slice(0,10);out.push({date,rows:grouped[date]||[]});}return out;},[data.rows,data.range?.from,data.range?.to]);
 const detailed=selectedDate?data.rows.filter((r:any)=>r.calendar_date===selectedDate):data.rows;
 async function generate(){await client.post('/workforce/calendar/generate');load();}async function publish(status:string){await client.put('/workforce/calendar/bulk-status',{from:data.range.from,to:data.range.to,status,scope:effectiveScope,warehouse_id:effectiveWarehouseId||null});load();}async function save(){try{await client.put(`/workforce/calendar/${editing.id}`,{...editing,unlock:editing.status==='LOCKED'});setEditing(null);load();}catch(e:any){setError(e.response?.data?.error||'Adjustment failed');}}
 async function audit(action_type:string,format:string){await client.post('/workforce/calendar/export-audit',{action_type,format,department_scope:effectiveScope,warehouse_id:effectiveWarehouseId||null,date_from:data.range.from,date_to:data.range.to});}
 async function print(){await audit('PRINT','PDF');window.print();}
 async function pdf(){await audit('DOWNLOAD','PDF');await downloadElementPdf('work-calendar-print',`${effectiveScope}-workday-calendar-${data.range.from}`,{orientation:'landscape'});}
 async function csv(){await audit('DOWNLOAD','CSV');const keys=['calendar_date','employee_code','employee_name','role_code','warehouse_name','shift_label','shift_start','shift_end','day_type','availability_status','reports_to_name','status'];const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const blob=new Blob([[keys.join(','),...data.rows.map((r:any)=>keys.map(k=>esc(r[k])).join(','))].join('\r\n')],{type:'text/csv'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${effectiveScope}-calendar-${data.range.from}.csv`;a.click();URL.revokeObjectURL(url);}
 async function excel(){await audit('DOWNLOAD','EXCEL');const keys=Object.keys(data.rows[0]||{}).filter(k=>!['id','created_by','updated_by'].includes(k));const html=`<table><tr>${keys.map(k=>`<th>${k.replace(/_/g,' ')}</th>`).join('')}</tr>${data.rows.map((r:any)=>`<tr>${keys.map(k=>`<td>${r[k]??''}</td>`).join('')}</tr>`).join('')}</table>`;const url=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel'})),a=document.createElement('a');a.href=url;a.download=`${effectiveScope}-calendar-${data.range.from}.xls`;a.click();URL.revokeObjectURL(url);}
 return <div><div className="mb-5 flex flex-wrap items-start justify-between gap-3 print:hidden"><div><h1 className="text-2xl font-bold">{admin?'Employee Calendar Management':`${scope} Workday Calendar`}</h1><p className="text-sm text-slate-500">Professional shift calendar with warehouse isolation, availability, rest days and reporting relationships.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={print}>Print Calendar</button><button className="btn-secondary" onClick={pdf}>Download PDF</button><button className="btn-secondary" onClick={excel}>Excel</button><button className="btn-secondary" onClick={csv}>CSV</button></div></div>
 <div className="card mb-4 flex flex-wrap gap-2 p-3 print:hidden">{admin&&<select className="input max-w-48" value={adminScope} onChange={e=>{setAdminScope(e.target.value as any);setWarehouseId('');}}><option>Warehouse</option><option>Procurement</option></select>}{effectiveScope==='Warehouse'&&data.warehouses?.length>0&&<select className="input max-w-64" value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}><option value="">All authorized warehouses</option>{data.warehouses.map((w:any)=><option value={w.id} key={w.id}>{w.warehouse_code} — {w.name}</option>)}</select>}<button className={period==='current'?'btn-primary':'btn-secondary'} onClick={()=>setPeriod('current')}>Current 15 Days</button><button className={period==='next'?'btn-primary':'btn-secondary'} onClick={()=>setPeriod('next')}>Next 15 Days</button><button className={view==='calendar'?'btn-primary':'btn-secondary'} onClick={()=>setView('calendar')}>Calendar View</button><button className={view==='roster'?'btn-primary':'btn-secondary'} onClick={()=>setView('roster')}>Detailed Roster</button>{admin&&<><button className="btn-secondary" onClick={generate}>Generate Monthly 15-Day Cycles</button>{['PUBLISHED'].map(s=><button key={s} className="btn-secondary" onClick={()=>publish(s)}>{s}</button>)}</>}<span className="ml-auto self-center text-sm text-slate-500">{data.range?.from} — {data.range?.to}</span></div>
 {error&&<div className="mb-3 rounded bg-rose-50 p-3 text-rose-700">{error}</div>}
 {!error&&!admin&&data.range&&!data.rows.length&&<div className="mb-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-900 shadow-sm"><div className="flex items-start gap-3"><span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-200 font-bold">!</span><div><h2 className="font-semibold">Workday calendar not published yet</h2><p className="mt-1 text-sm">The Supply Chain Manager is preparing the schedule for {data.range.from} to {data.range.to}. Draft and provisional schedules remain confidential until reviewed and published. Please check again later.</p></div></div></div>}
 <article id="work-calendar-print" className="controlled-print-document rounded-xl border border-slate-200 bg-white p-5"><header className="mb-5 flex items-center justify-between border-b border-indigo-100 pb-4"><div className="flex items-center gap-4"><CompanyLogo company={company} size="report"/><div><div className="text-xl font-bold text-slate-900">{company.company_name}</div><div className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">ProcuraFlow</div><h2 className="mt-1 text-lg font-semibold">{effectiveScope} Workday Calendar</h2></div></div><div className="text-right text-xs text-slate-600"><div><strong>Period:</strong> {data.range?.from} — {data.range?.to}</div><div><strong>Warehouse:</strong> {data.warehouses?.find((w:any)=>String(w.id)===warehouseId)?.name||'All authorized'}</div><div><strong>Generated:</strong> {new Date().toLocaleString()}</div><div><strong>Generated By:</strong> {user?.full_name}</div></div></header>
 {view==='calendar'?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{days.map(day=>{const counts=(code:string)=>day.rows.filter(r=>code==='OFF'?r.day_type==='OFF':r.shift_code===code&&r.day_type!=='OFF').length;return <button type="button" key={day.date} onClick={()=>setSelectedDate(day.date===selectedDate?'':day.date)} className={`min-h-52 rounded-xl border p-3 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${selectedDate===day.date?'border-indigo-500 ring-2 ring-indigo-100':'border-slate-200'}`}><div className="mb-3 flex items-start justify-between border-b pb-2"><div><strong className="text-base">{new Date(`${day.date}T00:00:00`).toLocaleDateString(undefined,{day:'2-digit',month:'short'})}</strong><div className="text-xs uppercase text-slate-500">{new Date(`${day.date}T00:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</div></div><StatusBadge status={day.rows[0]?.status}/></div>{['MORNING','AFTERNOON','EVENING','OFF'].map(code=><div key={code} className={`mb-1 flex justify-between rounded border px-2 py-1 text-xs font-semibold ${shiftTone[code]}`}><span>{code[0]+code.slice(1).toLowerCase()}</span><span>{counts(code)}</span></div>)}<div className="mt-2 space-y-1">{day.rows.filter(r=>r.day_type!=='OFF').slice(0,4).map(r=><div key={r.id} className={`truncate text-xs ${user?.full_name===r.employee_name?'font-bold text-indigo-700':'text-slate-600'}`}>{r.employee_name} · {r.shift_code||r.day_type}</div>)}{day.rows.length>4&&<div className="text-[10px] text-slate-400">+ more — select for details</div>}</div></button>})}</div>{selectedDate&&<div className="mt-5"><h3 className="mb-2 font-semibold">Detailed roster — {selectedDate}</h3><Roster rows={detailed} admin={admin} user={user} adjust={r=>setEditing({...r,reason:''})}/></div>}</>:<Roster rows={detailed} admin={admin} user={user} adjust={r=>setEditing({...r,reason:''})}/>}<footer className="mt-5 flex justify-between border-t border-slate-200 pt-3 text-[10px] text-slate-500"><span>Generated by ProcuraFlow · Generated By: {user?.full_name} · Generated On: {new Date().toLocaleString()}</span><span className="print-page-number">Page</span></footer></article>
 {editing&&<div className="fixed inset-0 z-[110] flex items-center justify-center bg-slate-950/50 p-4 print:hidden"><div className="card w-full max-w-lg space-y-3 p-5"><h2 className="font-bold">Manual Calendar Adjustment</h2><label className="block text-sm">Work Status<select className="input mt-1" value={editing.day_type} onChange={e=>setEditing({...editing,day_type:e.target.value})}>{['WORKDAY','OFF','HOLIDAY','HOLIDAY_WORKING'].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm">Shift<select className="input mt-1" value={editing.shift_id||''} onChange={e=>setEditing({...editing,shift_id:Number(e.target.value)||null})}><option value="">No shift</option>{refs.shifts.map((s:any)=><option key={s.id} value={s.id}>{s.shift_label}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-sm">Override Start<input type="time" className="input mt-1" value={editing.override_start_time||''} onChange={e=>setEditing({...editing,override_start_time:e.target.value})}/></label><label className="text-sm">Override End<input type="time" className="input mt-1" value={editing.override_end_time||''} onChange={e=>setEditing({...editing,override_end_time:e.target.value})}/></label></div><label className="block text-sm">Mandatory Reason<input className="input mt-1" value={editing.reason} onChange={e=>setEditing({...editing,reason:e.target.value})}/></label><label className="block text-sm">Remarks<textarea className="input mt-1" value={editing.remarks||''} onChange={e=>setEditing({...editing,remarks:e.target.value})}/></label><div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn-primary" onClick={save}>Save Protected Override</button></div></div></div>}</div>;
}
function Roster({rows,admin,user,adjust}:{rows:any[];admin:boolean;user:any;adjust:(r:any)=>void}){return <div className="overflow-x-auto"><table className="table-base"><thead><tr><th>Date</th><th>Employee</th><th>Role</th><th>Warehouse</th><th>Reports To</th><th>Shift</th><th>Time</th><th>Work / Availability</th><th>Source</th><th>Status</th>{admin&&<th>Action</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className={user?.full_name===r.employee_name?'bg-cyan-50':''}><td>{r.calendar_date}</td><td><strong>{r.employee_name}</strong><div className="text-xs text-slate-400">{r.employee_code}</div></td><td>{String(r.role_code).replace(/([a-z])([A-Z])/g,'$1 $2')}</td><td>{r.warehouse_name||'—'}</td><td>{r.reports_to_name?<>{r.reports_to_name}<div className="text-[10px] text-slate-400">{String(r.reports_to_role||'').replace(/([a-z])([A-Z])/g,'$1 $2')}</div></>:'—'}</td><td>{r.shift_label||'—'}</td><td>{r.override_start_time||r.shift_start||'—'} — {r.override_end_time||r.shift_end||'—'}</td><td><div>{r.day_type}</div><div className="text-[10px] text-slate-500">{r.availability_status||'Available'}</div></td><td>{r.assignment_source}{r.manual_override_yn?' · Manual Adjustment':''}</td><td><StatusBadge status={r.status}/></td>{admin&&<td><button className="btn-secondary" onClick={()=>adjust(r)}>Adjust</button></td>}</tr>)}</tbody></table></div>}
