import json
from pathlib import Path
from fastapi import APIRouter,HTTPException
from ..database import fetch_all
from ..security import User

router=APIRouter(prefix='/api/reports',tags=['reports'])
QUERIES=json.loads((Path(__file__).resolve().parents[1]/'report_queries.json').read_text(encoding='utf-8'))
EXEC={'executive-supply-chain-overview','open-po-commitments','purchase-by-category','purchase-by-month','inventory-aging','location-stock-executive','supplier-performance-executive','approval-governance','user-activity-log','employee-permissions','availability-conflicts','calendar-adjustments','helper-assignments','helper-shift-distribution','availability-impact','calendar-regeneration','calendar-download-audit','legacy-ledger-reconciliation','warehouse-access-verification','audit-finding-closure','backup-restore-history','audit-control-center'}
PROC={'pr-register','rfq-status','quotation-comparison','po-register','open-po','po-delivery-performance','price-variance','finance-payment-verification','purchase-summary','supplier-purchase-analysis','po-aging','invoice-register','po-vs-grn','po-vs-invoice','grn-vs-invoice','three-way-match','rfq-register','open-rfqs','supplier-participation','supplier-response-rate','award-recommendation','lowest-bid-vs-selected','split-award','procurement-savings','rfq-to-po-cycle-time','supplier-price-history','supplier-performance-by-rfq','cancelled-rfqs','rfq-audit-trail'}
WORK={'employee-availability','holiday-calendar','holiday-working','employee-workday','employee-schedule','combined-30-day-roster','department-shift-roster','employee-shift-distribution','shift-coverage','understaffed-shifts','uncovered-roles'}
FINANCE={'grni','invoice-without-grn','supplier-credit-note-register','accounts-payable-preparation','month-end-procurement-inventory-reconciliation','inventory-control-account','inventory-write-off','supplier-return-financial-impact','purchase-accrual','procurement-finance-reconciliation','executive-procurement-summary','executive-warehouse-inventory-summary','executive-control-risk-summary'}
def permitted(name,user):
    if name in EXEC and user['role']!='SupplyChainManager':raise HTTPException(403,f"Role '{user['role']}' is not permitted to perform this action")
    if name in PROC and user['role'] not in ['SupplyChainManager','PurchaseManager','PurchaseOfficer']:raise HTTPException(403,f"Role '{user['role']}' is not permitted to perform this action")
    if name in FINANCE and user['role']!='SupplyChainManager':raise HTTPException(403,f"Role '{user['role']}' is not permitted to perform this action")
def make_handler(name,sql):
    def handler(user:User):permitted(name,user);return fetch_all(sql)
    handler.__name__='report_'+name.replace('-','_');return handler
for _name,_sql in QUERIES.items():router.add_api_route('/'+_name,make_handler(_name,_sql),methods=['GET'])

SCOPED={
'grn-register':"SELECT g.grn_number,g.grn_date,po.po_number,s.name supplier_name,g.delivery_note,ROUND(SUM(gi.accepted_qty*gi.unit_cost),2) accepted_value FROM grns g JOIN purchase_orders po ON po.id=g.po_id JOIN suppliers s ON s.id=g.supplier_id JOIN grn_items gi ON gi.grn_id=g.id AND gi.warehouse_id IN({marks}) GROUP BY g.id ORDER BY g.id DESC",
'daily-receiving':"SELECT g.grn_date date,g.grn_number,i.item_code,w.warehouse_code,w.name warehouse_name,w.site_name,l.code location_code,gi.quantity_received received,gi.accepted_qty accepted,gi.rejected_qty rejected FROM grn_items gi JOIN grns g ON g.id=gi.grn_id JOIN items i ON i.id=gi.item_id JOIN warehouses w ON w.id=gi.warehouse_id LEFT JOIN locations l ON l.id=gi.location_id WHERE gi.warehouse_id IN({marks}) ORDER BY g.grn_date DESC,g.id DESC",
'daily-issues':"SELECT mi.issue_date date,mi.issue_number,e.name employee_name,d.name department_name,i.item_code,w.warehouse_code,w.name warehouse_name,w.site_name,l.code location_code,mii.quantity,mii.value FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id JOIN employees e ON e.id=mi.employee_id LEFT JOIN departments d ON d.id=e.department_id JOIN items i ON i.id=mii.item_id JOIN warehouses w ON w.id=mii.warehouse_id LEFT JOIN locations l ON l.id=mii.location_id WHERE mi.status='Posted' AND mii.warehouse_id IN({marks}) ORDER BY mi.id DESC",
'returns-report':"SELECT r.return_number,r.return_date,e.name employee_name,i.item_code,r.quantity,r.condition,w.name warehouse_name FROM returns r JOIN items i ON i.id=r.item_id LEFT JOIN employees e ON e.id=r.employee_id LEFT JOIN warehouses w ON w.id=r.warehouse_id WHERE r.warehouse_id IN({marks}) ORDER BY r.id DESC",
'adjustments-report':"SELECT a.adjustment_number,a.adjustment_date,i.item_code,w.name warehouse_name,a.quantity_change,a.reason,a.status FROM stock_adjustments a JOIN items i ON i.id=a.item_id JOIN warehouses w ON w.id=a.warehouse_id WHERE a.warehouse_id IN({marks}) ORDER BY a.id DESC",
'stock-ledger':"SELECT sl.created_at,sl.transaction_type,i.item_code,i.description,w.warehouse_code,w.name warehouse_name,w.site_name,l.code location_code,sl.quantity_change,sl.unit_cost,ROUND(sl.quantity_change*sl.unit_cost,2) total_value,sl.reference_number,u.full_name posted_by FROM stock_ledger sl JOIN items i ON i.id=sl.item_id JOIN warehouses w ON w.id=sl.warehouse_id LEFT JOIN locations l ON l.id=sl.location_id LEFT JOIN users u ON u.id=sl.created_by WHERE sl.warehouse_id IN({marks}) ORDER BY sl.id DESC",
'low-stock':"SELECT i.item_code,i.description,i.reorder_level,COALESCE(SUM(s.quantity),0) current_quantity FROM items i LEFT JOIN inventory_stock s ON s.item_id=i.id AND s.warehouse_id IN({marks}) WHERE i.deleted_at IS NULL GROUP BY i.id HAVING current_quantity<=i.reorder_level ORDER BY i.item_code",
'batch-report':"SELECT i.item_code,il.batch,il.expiry_date,w.warehouse_code,w.name warehouse_name,w.site_name,l.code location_code,SUM(il.quantity_remaining) quantity,il.unit_cost FROM inventory_layers il JOIN items i ON i.id=il.item_id JOIN warehouses w ON w.id=il.warehouse_id LEFT JOIN locations l ON l.id=il.location_id WHERE il.batch IS NOT NULL AND il.warehouse_id IN({marks}) GROUP BY i.id,il.batch,il.expiry_date,w.id,l.id,il.unit_cost",
'cycle-count-accuracy':"SELECT cc.count_number,cc.count_date,w.name warehouse_name,COUNT(cci.id) lines,SUM(CASE WHEN ABS(COALESCE(cci.variance,0))<.0001 THEN 1 ELSE 0 END) accurate_lines,ROUND(100.0*SUM(CASE WHEN ABS(COALESCE(cci.variance,0))<.0001 THEN 1 ELSE 0 END)/COUNT(cci.id),2) accuracy_pct FROM cycle_counts cc JOIN cycle_count_items cci ON cci.count_id=cc.id JOIN warehouses w ON w.id=cc.warehouse_id WHERE cc.status='Approved' AND cc.warehouse_id IN({marks}) GROUP BY cc.id ORDER BY cc.id DESC",
'tool-condition':"SELECT tool_code,serial_number,make,model,condition,issue_date,return_date,calibration_due_date FROM tools WHERE condition IN('Damaged','Lost','Needs Repair') AND warehouse_id IN({marks}) ORDER BY tool_code"}
def make_scoped(name,sql):
    def handler(user:User):
        ids=user['warehouse_ids'];
        if not ids:return []
        return fetch_all(sql.format(marks=','.join('?' for _ in ids)),ids)
    handler.__name__='scoped_'+name.replace('-','_');return handler
for _name,_sql in SCOPED.items():
    if _name not in QUERIES:router.add_api_route('/'+_name,make_scoped(_name,_sql),methods=['GET'])

SIMPLE={
'invoice-register':'SELECT inv.*,s.name supplier_name,po.po_number,g.grn_number FROM invoices inv JOIN suppliers s ON s.id=inv.supplier_id JOIN purchase_orders po ON po.id=inv.po_id LEFT JOIN grns g ON g.id=inv.grn_id ORDER BY inv.id DESC',
'po-aging':"SELECT po.po_number,po.po_date,s.name supplier_name,po.total_amount,po.status,CAST(julianday('now')-julianday(po.po_date)AS INTEGER)age_days FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.status NOT IN('Closed','Rejected')ORDER BY age_days DESC",
'purchase-summary':"SELECT strftime('%Y-%m',po_date)period,COUNT(*)po_count,ROUND(SUM(total_amount),2)total_value FROM purchase_orders WHERE status IN('Approved','Printed','Closed')GROUP BY period ORDER BY period DESC",
'supplier-purchase-analysis':"SELECT s.supplier_code,s.name supplier_name,COUNT(po.id)po_count,ROUND(COALESCE(SUM(po.total_amount),0),2)total_value FROM suppliers s LEFT JOIN purchase_orders po ON po.supplier_id=s.id AND po.status IN('Approved','Printed','Closed')WHERE s.deleted_at IS NULL GROUP BY s.id ORDER BY total_value DESC",
'fifo-valuation':'SELECT i.item_code,i.description,w.name warehouse_name,il.batch,il.expiry_date,il.received_date,il.quantity_remaining quantity,il.unit_cost,ROUND(il.quantity_remaining*il.unit_cost,2)value FROM inventory_layers il JOIN items i ON i.id=il.item_id JOIN warehouses w ON w.id=il.warehouse_id WHERE il.quantity_remaining>0 ORDER BY il.received_date,il.id',
'stock-balance':'SELECT i.item_code,i.description,w.name warehouse_name,l.code location_code,s.quantity FROM inventory_stock s JOIN items i ON i.id=s.item_id JOIN warehouses w ON w.id=s.warehouse_id LEFT JOIN locations l ON l.id=s.location_id WHERE s.quantity<>0 ORDER BY i.item_code',
'bin-stock':'SELECT w.name warehouse_name,l.code bin_code,i.item_code,i.description,s.quantity FROM inventory_stock s JOIN warehouses w ON w.id=s.warehouse_id JOIN items i ON i.id=s.item_id LEFT JOIN locations l ON l.id=s.location_id WHERE s.quantity<>0 ORDER BY w.name,l.code,i.item_code',
'currency-master':'SELECT * FROM currencies ORDER BY currency_code','exchange-rate-master':'SELECT * FROM exchange_rates ORDER BY effective_date DESC',
'consumption-by-employee':"SELECT e.employee_code,e.name employee_name,ROUND(SUM(mii.value),2)total_value,SUM(mii.quantity)total_quantity FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id JOIN employees e ON e.id=mi.employee_id WHERE mi.status='Posted'GROUP BY e.id ORDER BY total_value DESC",
'consumption-by-department':"SELECT d.name department_name,ROUND(SUM(mii.value),2)total_value,SUM(mii.quantity)total_quantity FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id JOIN employees e ON e.id=mi.employee_id JOIN departments d ON d.id=e.department_id WHERE mi.status='Posted'GROUP BY d.id ORDER BY total_value DESC",
'transfers-report':'SELECT t.*,i.item_code,fw.name from_warehouse_name,tw.name to_warehouse_name FROM transfers t JOIN items i ON i.id=t.item_id JOIN warehouses fw ON fw.id=t.from_warehouse_id JOIN warehouses tw ON tw.id=t.to_warehouse_id ORDER BY t.id DESC',
'transfer-receipts-report':'SELECT tr.*,t.transfer_number,i.item_code,w.name receiving_warehouse,l.code receiving_bin FROM transfer_receipts tr JOIN transfers t ON t.id=tr.transfer_id JOIN items i ON i.id=tr.item_id JOIN warehouses w ON w.id=tr.warehouse_id JOIN locations l ON l.id=tr.location_id ORDER BY tr.id DESC'}
SIMPLE.update({
'grni':"SELECT g.grn_number,g.grn_date,po.po_number,s.name supplier_name,ROUND(SUM(gi.accepted_qty*gi.unit_cost),2) received_value,'Invoice Not Recorded' status FROM grns g JOIN purchase_orders po ON po.id=g.po_id JOIN suppliers s ON s.id=g.supplier_id JOIN grn_items gi ON gi.grn_id=g.id WHERE NOT EXISTS(SELECT 1 FROM invoices inv WHERE inv.po_id=po.id AND(inv.grn_id=g.id OR inv.grn_id IS NULL)) GROUP BY g.id ORDER BY g.grn_date DESC",
'invoice-without-grn':"SELECT inv.invoice_number,inv.invoice_date,po.po_number,s.name supplier_name,inv.invoice_total invoice_value,inv.match_status status FROM invoices inv JOIN purchase_orders po ON po.id=inv.po_id JOIN suppliers s ON s.id=inv.supplier_id WHERE inv.grn_id IS NULL AND NOT EXISTS(SELECT 1 FROM grns g WHERE g.po_id=inv.po_id) ORDER BY inv.invoice_date DESC",
'supplier-credit-note-register':"SELECT r.return_number,r.return_date,s.name supplier_name,i.item_code,i.description,r.quantity,ROUND(r.quantity*COALESCE((SELECT mii.value/NULLIF(mii.quantity,0) FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id WHERE mi.employee_id=r.employee_id AND mii.item_id=r.item_id ORDER BY mi.id DESC LIMIT 1),i.standard_cost,0),2) return_value,'Credit Note Not Recorded' credit_note_status FROM returns r JOIN items i ON i.id=r.item_id LEFT JOIN suppliers s ON s.id=(SELECT po.supplier_id FROM purchase_orders po JOIN po_items pi ON pi.po_id=po.id WHERE pi.item_id=r.item_id ORDER BY po.id DESC LIMIT 1) ORDER BY r.return_date DESC",
'accounts-payable-preparation':"SELECT inv.invoice_number,inv.invoice_date,po.po_number,g.grn_number,s.name supplier_name,inv.invoice_total invoice_value,inv.match_status control_status,CASE WHEN inv.match_status='Matched' THEN 'Ready for Finance - External Process' ELSE 'Control Exception' END handoff_status FROM invoices inv JOIN purchase_orders po ON po.id=inv.po_id JOIN suppliers s ON s.id=inv.supplier_id LEFT JOIN grns g ON g.id=inv.grn_id ORDER BY inv.invoice_date DESC",
'month-end-procurement-inventory-reconciliation':"SELECT 'Opening Inventory' movement,ROUND(COALESCE((SELECT SUM(quantity_remaining*unit_cost)FROM inventory_layers WHERE received_date<date('now','start of month')),0),2)value UNION ALL SELECT 'Receipts',ROUND(COALESCE((SELECT SUM(accepted_qty*unit_cost)FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.grn_date>=date('now','start of month')),0),2) UNION ALL SELECT 'Material Issues',ROUND(COALESCE((SELECT SUM(total_value)FROM material_issues WHERE status='Posted'AND issue_date>=date('now','start of month')),0),2) UNION ALL SELECT 'Closing Inventory',ROUND(COALESCE((SELECT SUM(quantity_remaining*unit_cost)FROM inventory_layers),0),2) UNION ALL SELECT 'Open PO Commitments',ROUND(COALESCE((SELECT SUM(total_amount)FROM purchase_orders WHERE status IN('PendingApproval','Approved','Printed')),0),2)",
'inventory-control-account':"SELECT i.item_code,i.description,w.name warehouse_name,ROUND(SUM(s.quantity),4)stock_quantity,ROUND(COALESCE((SELECT SUM(il.quantity_remaining)FROM inventory_layers il WHERE il.item_id=i.id AND il.warehouse_id=w.id),0),4)fifo_quantity,ROUND(SUM(s.quantity)-COALESCE((SELECT SUM(il.quantity_remaining)FROM inventory_layers il WHERE il.item_id=i.id AND il.warehouse_id=w.id),0),4)quantity_variance,ROUND(COALESCE((SELECT SUM(il.quantity_remaining*il.unit_cost)FROM inventory_layers il WHERE il.item_id=i.id AND il.warehouse_id=w.id),0),2)closing_value FROM inventory_stock s JOIN items i ON i.id=s.item_id JOIN warehouses w ON w.id=s.warehouse_id GROUP BY i.id,w.id ORDER BY i.item_code,w.name",
'inventory-write-off':"SELECT a.adjustment_number,a.adjustment_date,i.item_code,i.description,w.name warehouse_name,a.quantity_change,ROUND(ABS(a.quantity_change)*COALESCE(i.standard_cost,0),2)write_off_value,a.reason,a.status FROM stock_adjustments a JOIN items i ON i.id=a.item_id JOIN warehouses w ON w.id=a.warehouse_id WHERE a.quantity_change<0 AND(lower(a.reason)LIKE '%damage%'OR lower(a.reason)LIKE '%lost%'OR lower(a.reason)LIKE '%expir%'OR lower(a.reason)LIKE '%obsolet%'OR lower(a.reason)LIKE '%write%') ORDER BY a.adjustment_date DESC",
'supplier-return-financial-impact':"SELECT r.return_number,r.return_date,i.item_code,i.description,r.quantity,ROUND(r.quantity*COALESCE(i.standard_cost,0),2)return_value,s.name supplier_name,po.po_number,(SELECT g.grn_number FROM grns g WHERE g.po_id=po.id ORDER BY g.id DESC LIMIT 1)grn_number,'Recovery Pending' recovery_status FROM returns r JOIN items i ON i.id=r.item_id LEFT JOIN po_items pi ON pi.item_id=r.item_id LEFT JOIN purchase_orders po ON po.id=pi.po_id LEFT JOIN suppliers s ON s.id=po.supplier_id GROUP BY r.id ORDER BY r.return_date DESC",
'purchase-accrual':"SELECT g.grn_number,g.grn_date,po.po_number,s.name supplier_name,ROUND(SUM(gi.accepted_qty*gi.unit_cost),2)accrual_value FROM grns g JOIN purchase_orders po ON po.id=g.po_id JOIN suppliers s ON s.id=g.supplier_id JOIN grn_items gi ON gi.grn_id=g.id WHERE NOT EXISTS(SELECT 1 FROM invoices inv WHERE inv.po_id=po.id) GROUP BY g.id ORDER BY g.grn_date DESC",
'procurement-finance-reconciliation':"SELECT po.po_number,s.name supplier_name,ROUND(po.total_amount,2)po_value,ROUND(COALESCE((SELECT SUM(gi.accepted_qty*gi.unit_cost)FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.po_id=po.id),0),2)received_value,ROUND(COALESCE((SELECT SUM(inv.invoice_total)FROM invoices inv WHERE inv.po_id=po.id),0),2)invoiced_value,ROUND(COALESCE((SELECT SUM(CASE WHEN inv.match_status='Matched'THEN inv.invoice_total ELSE 0 END)FROM invoices inv WHERE inv.po_id=po.id),0),2)approved_payable_value FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id ORDER BY po.po_date DESC",
'executive-procurement-summary':"SELECT ROUND(COALESCE((SELECT SUM(total_amount)FROM purchase_orders WHERE status IN('Approved','Printed','Closed')),0),2)total_purchase_value,(SELECT COUNT(*)FROM purchase_requisitions)prs_raised,(SELECT COUNT(*)FROM approval_log WHERE document_type='PR'AND decision='Approved')prs_approved,(SELECT COUNT(*)FROM approval_log WHERE document_type='PR'AND decision='Pending')prs_pending,(SELECT COUNT(*)FROM purchase_orders)pos_created,ROUND(COALESCE((SELECT SUM(total_amount)FROM purchase_orders WHERE status IN('PendingApproval','Approved','Printed')),0),2)open_po_commitments,(SELECT COUNT(*)FROM purchase_orders WHERE status IN('Approved','Printed')AND committed_delivery_date<date('now'))overdue_pos",
'executive-warehouse-inventory-summary':"SELECT ROUND(COALESCE((SELECT SUM(quantity_remaining*unit_cost)FROM inventory_layers),0),2)closing_inventory_value,ROUND(COALESCE((SELECT SUM(accepted_qty*unit_cost)FROM grn_items gi JOIN grns g ON g.id=gi.grn_id WHERE g.grn_date>=date('now','start of month')),0),2)monthly_receipts,ROUND(COALESCE((SELECT SUM(total_value)FROM material_issues WHERE status='Posted'AND issue_date>=date('now','start of month')),0),2)monthly_issues,(SELECT COUNT(*)FROM items i WHERE i.deleted_at IS NULL AND COALESCE((SELECT SUM(quantity)FROM inventory_stock s WHERE s.item_id=i.id),0)<=i.reorder_level)low_stock_items,(SELECT COUNT(*)FROM stock_adjustments WHERE status='Approved')approved_adjustments",
'executive-control-risk-summary':"SELECT(SELECT COUNT(*)FROM purchase_orders WHERE status IN('Approved','Printed')AND committed_delivery_date<date('now'))overdue_pos,(SELECT COUNT(*)FROM invoices WHERE match_status<>'Matched')three_way_match_exceptions,(SELECT COUNT(*)FROM stock_adjustments WHERE status='Pending')pending_stock_adjustments,(SELECT COUNT(*)FROM sod_conflict_reviews WHERE status NOT IN('FALSE POSITIVE','APPROVED BUSINESS EXCEPTION'))sod_conflicts,(SELECT COUNT(*)FROM audit_finding_closure WHERE status<>'RESOLVED')unresolved_audit_findings",
'public-holidays-by-location':"SELECT h.holiday_name,h.holiday_type,h.country_code,h.region,h.holiday_date official_date,COALESCE(h.observed_date,h.holiday_date)observed_date,h.day_scope,h.start_time,h.end_time,h.government_yn,h.statutory_yn,h.source,h.active_yn FROM holidays h ORDER BY observed_date,h.country_code,h.region,h.holiday_name",
'warehouse-operating-calendar':"SELECT w.warehouse_code,w.name warehouse_name,w.country_code,w.region_province,w.time_zone,s.weekday,s.is_open,s.open_time,s.close_time,s.cross_midnight_yn FROM warehouses w JOIN warehouse_operating_schedules s ON s.warehouse_id=w.id WHERE w.deleted_at IS NULL ORDER BY w.name,s.weekday",
'holiday-work-exceptions':"SELECT h.holiday_name,COALESCE(h.observed_date,h.holiday_date)holiday_date,w.name warehouse_name,e.employee_code,e.name employee_name,s.shift_label,x.reason,u.full_name approved_by,x.approved_at FROM holiday_work_exceptions x JOIN holidays h ON h.id=x.holiday_id JOIN warehouses w ON w.id=x.warehouse_id LEFT JOIN employees e ON e.id=x.employee_id LEFT JOIN shifts s ON s.id=x.shift_id JOIN users u ON u.id=x.approved_by ORDER BY holiday_date DESC,w.name",
'scheduled-month-end-backups':"SELECT cycle_id,scheduled_at_utc,backup_time_zone,status,warning_30_at,warning_20_at,warning_10_at,started_at,completed_at,verification_result,error_message FROM backup_cycles ORDER BY scheduled_at_utc DESC",
'outstanding-returnables':"SELECT e.employee_code,e.name employee_name,i.item_code,SUM(mii.quantity)-COALESCE((SELECT SUM(r.quantity)FROM returns r WHERE r.employee_id=e.id AND r.item_id=i.id),0)outstanding_quantity FROM material_issue_items mii JOIN material_issues mi ON mi.id=mii.issue_id JOIN employees e ON e.id=mi.employee_id JOIN items i ON i.id=mii.item_id WHERE mi.status='Posted'AND i.consumable_returnable='Returnable'GROUP BY e.id,i.id HAVING outstanding_quantity>0",
'employee-shift-distribution':"SELECT e.employee_code,e.name employee_name,d.name department_name,c.role_code,SUM(s.shift_code='MORNING')morning_shifts,SUM(s.shift_code='AFTERNOON')afternoon_shifts,SUM(s.shift_code='EVENING')evening_shifts,COUNT(c.shift_id)total_shifts FROM employee_work_calendar c JOIN employees e ON e.id=c.employee_id JOIN departments d ON d.id=c.department_id LEFT JOIN shifts s ON s.id=c.shift_id GROUP BY e.id ORDER BY d.name,e.name",
'duplicate-item-analysis':"SELECT p.item_code primary_item_code,p.description primary_item_description,d.item_code possible_duplicate_item_code,d.description possible_duplicate_description,r.similarity_score,r.match_type,r.review_status status FROM item_duplicate_reviews r JOIN items p ON p.id=r.primary_item_id JOIN items d ON d.id=r.possible_duplicate_item_id ORDER BY r.similarity_score DESC",
'system-integrity-summary':"SELECT(SELECT COUNT(*)FROM audit_finding_closure WHERE status<>'RESOLVED')open_audit_findings,(SELECT COUNT(*)FROM legacy_ledger_reconciliation WHERE resolution_status<>'RESOLVED')ledger_warnings,(SELECT COUNT(*)FROM sod_conflict_reviews WHERE status NOT IN('FALSE POSITIVE','APPROVED BUSINESS EXCEPTION'))sod_conflicts,(SELECT COUNT(*)FROM accounting_periods WHERE status='OPEN')open_periods",
'audit-control-center':"SELECT finding_id reference,severity,issue description,status,residual_risk FROM audit_finding_closure UNION ALL SELECT warning_key,'HIGH',root_cause_classification,resolution_status,risk_level FROM legacy_ledger_reconciliation ORDER BY severity,reference"})
SIMPLE.update({
'rfq-register':"SELECT r.rfq_number,pr.pr_number,r.issue_date,r.closing_date,r.required_delivery_date,r.currency,r.workflow_status,COUNT(DISTINCT rs.supplier_id)suppliers_invited,COUNT(DISTINCT q.id)quotation_lines FROM rfqs r LEFT JOIN purchase_requisitions pr ON pr.id=r.pr_id LEFT JOIN rfq_suppliers rs ON rs.rfq_id=r.id LEFT JOIN supplier_quotations q ON q.rfq_id=r.id AND q.active_yn=1 GROUP BY r.id ORDER BY r.id DESC",
'open-rfqs':"SELECT r.rfq_number,pr.pr_number,r.closing_date,r.required_delivery_date,r.workflow_status,COUNT(DISTINCT rs.supplier_id)suppliers_invited FROM rfqs r LEFT JOIN purchase_requisitions pr ON pr.id=r.pr_id LEFT JOIN rfq_suppliers rs ON rs.rfq_id=r.id WHERE r.workflow_status NOT IN('Closed','Cancelled') GROUP BY r.id ORDER BY r.closing_date",
'supplier-participation':"SELECT s.supplier_code,s.name supplier_name,COUNT(DISTINCT rs.rfq_id)rfqs_invited,COUNT(DISTINCT q.rfq_id)rfqs_responded FROM suppliers s LEFT JOIN rfq_suppliers rs ON rs.supplier_id=s.id LEFT JOIN supplier_quotations q ON q.supplier_id=s.id GROUP BY s.id ORDER BY rfqs_invited DESC",
'supplier-response-rate':"SELECT s.supplier_code,s.name supplier_name,COUNT(DISTINCT rs.rfq_id)invitations,COUNT(DISTINCT q.rfq_id)responses,ROUND(CASE WHEN COUNT(DISTINCT rs.rfq_id)=0 THEN 0 ELSE 100.0*COUNT(DISTINCT q.rfq_id)/COUNT(DISTINCT rs.rfq_id)END,2)response_rate_pct FROM suppliers s LEFT JOIN rfq_suppliers rs ON rs.supplier_id=s.id LEFT JOIN supplier_quotations q ON q.supplier_id=s.id GROUP BY s.id ORDER BY response_rate_pct DESC",
'award-recommendation':"SELECT r.rfq_number,i.item_code,s.name recommended_supplier,a.awarded_quantity,a.recommendation_reason,a.non_lowest_justification,a.status,u.full_name recommended_by FROM rfq_awards a JOIN rfqs r ON r.id=a.rfq_id JOIN items i ON i.id=a.item_id JOIN suppliers s ON s.id=a.supplier_id JOIN users u ON u.id=a.recommended_by ORDER BY a.id DESC",
'lowest-bid-vs-selected':"SELECT r.rfq_number,i.item_code,s.name selected_supplier,q.price selected_price,a.non_lowest_justification,(SELECT MIN(q2.price)FROM supplier_quotations q2 WHERE q2.rfq_id=a.rfq_id AND q2.item_id=a.item_id AND q2.active_yn=1)lowest_unit_price FROM rfq_awards a JOIN rfqs r ON r.id=a.rfq_id JOIN items i ON i.id=a.item_id JOIN suppliers s ON s.id=a.supplier_id JOIN supplier_quotations q ON q.id=a.quotation_id WHERE a.status<>'Rejected' ORDER BY a.id DESC",
'split-award':"SELECT r.rfq_number,i.item_code,COUNT(DISTINCT a.supplier_id)suppliers_awarded,SUM(a.awarded_quantity)total_awarded_quantity,GROUP_CONCAT(s.name,', ')awarded_suppliers FROM rfq_awards a JOIN rfqs r ON r.id=a.rfq_id JOIN items i ON i.id=a.item_id JOIN suppliers s ON s.id=a.supplier_id WHERE a.status='Approved' GROUP BY a.rfq_id,a.item_id HAVING COUNT(DISTINCT a.supplier_id)>1",
'procurement-savings':"SELECT r.rfq_number,ROUND(SUM((highest.highest_cost-selected.selected_cost)),2)evaluated_savings FROM rfqs r JOIN(SELECT rfq_id,item_id,MAX(price*quoted_quantity-discount+freight+other_charges)highest_cost FROM supplier_quotations WHERE active_yn=1 GROUP BY rfq_id,item_id)highest ON highest.rfq_id=r.id JOIN(SELECT a.rfq_id,a.item_id,SUM(q.price*a.awarded_quantity-q.discount+q.freight+q.other_charges)selected_cost FROM rfq_awards a JOIN supplier_quotations q ON q.id=a.quotation_id WHERE a.status='Approved' GROUP BY a.rfq_id,a.item_id)selected ON selected.rfq_id=highest.rfq_id AND selected.item_id=highest.item_id GROUP BY r.id",
'rfq-to-po-cycle-time':"SELECT r.rfq_number,MIN(po.po_number)purchase_order,CAST(julianday(MIN(po.created_at))-julianday(COALESCE(r.issue_date,r.rfq_date))AS INTEGER)cycle_days FROM rfqs r JOIN purchase_orders po ON po.rfq_id=r.id GROUP BY r.id ORDER BY cycle_days DESC",
'supplier-price-history':"SELECT s.name supplier_name,i.item_code,q.quotation_date,q.quotation_number,q.revision_number,q.currency,q.price,q.quoted_quantity FROM supplier_quotations q JOIN suppliers s ON s.id=q.supplier_id JOIN items i ON i.id=q.item_id ORDER BY q.quotation_date DESC,q.id DESC",
'supplier-performance-by-rfq':"SELECT r.rfq_number,s.name supplier_name,rs.response_status,s.rating supplier_rating,COUNT(q.id)quoted_lines,ROUND(AVG(q.price),2)average_unit_price FROM rfq_suppliers rs JOIN rfqs r ON r.id=rs.rfq_id JOIN suppliers s ON s.id=rs.supplier_id LEFT JOIN supplier_quotations q ON q.rfq_id=r.id AND q.supplier_id=s.id AND q.active_yn=1 GROUP BY r.id,s.id ORDER BY r.id DESC",
'cancelled-rfqs':"SELECT r.rfq_number,pr.pr_number,r.issue_date,r.closing_date,r.notes,r.updated_at cancelled_at FROM rfqs r LEFT JOIN purchase_requisitions pr ON pr.id=r.pr_id WHERE r.workflow_status='Cancelled' ORDER BY r.updated_at DESC",
'rfq-audit-trail':"SELECT r.rfq_number,a.changed_at,a.action,u.full_name changed_by,a.old_values,a.new_values FROM audit_log a JOIN rfqs r ON(a.table_name='rfqs'AND a.record_id=r.id)LEFT JOIN users u ON u.id=a.changed_by ORDER BY a.id DESC"})
for _name,_sql in SIMPLE.items():
    if _name not in QUERIES:router.add_api_route('/'+_name,make_handler(_name,_sql),methods=['GET'])
